Expensify/expensify-common

- .github/workflows/cla.yml
@rafecolton - Will you please review?
Similar to https://github.com/Expensify/react-native-onyx/pull/27
Let's make a few changes in the settings:
1. Remove `BOTIFY` secret from this repo
3. Add `OS_BOTIFY_TOKEN`
4. Then let's merge this PR and I will verify everything is good.
> Move from BOTIFY to OS_BOTIFY

- package-lock.json
- package.json
@Jag96 - Will you please reivew?
Since `simply-deferred` is public we can use https to clone it instead of ssh, once this is merged it will allow `expensify.cash` and `react-native-onyx` to build without any need for SSH keys.
https://github.com/Expensify/react-native-onyx/runs/1579163896#step:5:5
1. Make sure npm install works
2. Make sure actions pass
> Use https for public dependency

- lib/API.jsx
As part of https://github.com/Expensify/Expensify/issues/146558, I will be adding the request a call modal on the signup page.  I need to add a couple new homepage API endpoints to accomplish that which are to request a setup call, and to get the active policy ID
Part of https://github.com/Expensify/Expensify/issues/146558
Tested the changes as part of the Web-E PR and successfully got reached both endpoints
No QA needed
> Add API Endpoints for Requesting a Setup Call and getting Active PolicyID [No QA]

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.js
**Causing text wrapping issues in Expensify.cash**
@marcaaron Please review it.
After testing I found out the using `&nbsp;` chars instead on spaces are creating a one big line which as a result will break into new lines on the browser or rendering engine's mercy. Usually, the result would be that words will break into multiple lines.
Fixes https://github.com/Expensify/Expensify.cash/issues/993
Jest tests
2. What tests did you perform that validates your change worked?
I performed visual testing on the Expensify.cash where results are as follows:
The first one is the issue and the second one is the result. Same result on the mobile app.
> Replaced non-breaking spaces with equivalent ascii space Fixes Expensify/Expensify.cash/#993

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.js
This PR fixed email link rendering bug by adding additional email regular expressions to the current rules.
https://github.com/Expensify/Expensify.cash/issues/990
> fix email rendering bug

- .github/workflows/cla.yml
Please review @coleaeason 
Adds @CLABotify to handle CLA signatures
Fixes 1 /3 of https://github.com/Expensify/Expensify/issues/148866
1. Make a PR (e.g. this one)
2. Make sure CLA botify passes, if it does, it means the token has access to the repo.
> Add @CLABotify and apply new version for CLA Assistant

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.js
@roryabraham @kadiealexander  will you please review this?
Fixed the URL highlighting issue when URL's included `:`, `~`, `/` _(on param)_, `[` and `]`. 
Added ability to use `:` and `/` on a link text (between `[` and `]`).
Made sure all three URL's mentioned on the issue page worked, without causing regressions. Added tests for all this cases, and plus a couple more I could think of (and was having trouble with).
Fixes [#1234](https://github.com/Expensify/Expensify.cash/issues/1234)
Added quite a number of test URL's on `ExpensiMark-test.js`.
On the gifs presented next, the following string was pasted on all the platforms:
```
Testing …
```
> Fixed URL highlight

- lib/components/form/element/onOffSwitch.jsx
- lib/components/form/element/switch.js
@ctkochan22 you've been PB'd
This is part of a solution to https://github.com/Expensify/Expensify/issues/153817
In reality, the issue was just a miscommunication/misunderstanding on the part of our success agents. To prevent such confusion in the future, we can display a tooltip when on the `OnOffSwitch` when it's disabled. This PR sets up the `OnOffSwitch` so that it can use tooltips.
$ https://github.com/Expensify/Expensify/issues/153817
No automated tests. Was tested in Web-Expensify – one `OnOffSwitch` was provided the `tooltipText` prop, the other two were not.
https://user-images.githubusercontent.com/47436092/107329559-2cc0b500-6a65-11eb-834a-bbd7d6f3c33c.mov
None.
> Setup OnOffSwitch component with tooltips

- lib/CONST.jsx
- package-lock.json
- package.json
$ https://github.com/Expensify/Expensify/issues/153792
Test in conjunction with `Web-Expensify` PR [here](https://github.com/Expensify/Web-Expensify/pull/30229)
1. Start out on Web-E `master` and verify the values of `CONST.DATE.DEFAULT_START_DATE` and `CONST.DATE.DEFAULT_END_DATE` in the JS console.
2. Switch to the test branch, `npm install`, and `grunt watch`
3. Verify the values are the same
**Before:**
**After:**
❌
> Remove moment from expensify-common

- .github/workflows/cla.yml
This restricts the CLA bot from running only on PR comments or events, if you were to comment on an issue you'd get an email saying the GitHub action failed on your issue comment.
Fixes https://github.com/Expensify/Expensify/issues/154742
1. I edited the logic in [my public test repo here to match the logic in this PR](https://github.com/Andrew-Test-Org/Public-Test-Repo/blob/main/.github/workflows/CLA.yml)
2. I then pushed a [PR that had the CLA run](https://github.com/Andrew-Test-Org/Public-Test-Repo/actions/runs/590183836) ✅
3. I then [left a comment on a PR that ran the CLA](https://github.com/Andrew-Test-Org/Public-Test-Repo/actions/runs/590184939) ✅ 
4. I then [left a comment on an issue and verified the CLA did not run](https://github.com/Andrew-Test-Org/Public-Test-Repo/actions/runs …
> Only run CLA on PR comments or events

- lib/CONST.jsx
Pullerbear review (@thienlnam)
Needed for https://github.com/Expensify/Expensify/issues/150106
Will only be testable on Web-E after updating it to use the latest expensify-common, but here are the steps:
1. Create a new policy
2. Go to Connections  > QuickBooks Desktop, expand the section
3. Click on the "Need to reinstall the Sync Manager? Click here" link
4. Make sure something downloads
> Update QBD Sync Manager version

- .github/workflows/cla.yml
We no longer need to whitelist @botify as it does not commit or merge pull requests in this repo anymore, so I've removed it to make sure we are compliant!
> Remove botify from CLA

- lib/CONST.jsx
Pullerbear review
For https://github.com/Expensify/Expensify/issues/150106#issuecomment-789992405
Will only be testable on Web-E after updating it to use the latest expensify-common, but here are the steps:
1. Create a new policy or open an existing one
2. Go to Connections  > QuickBooks Desktop, expand the section
3. Click on the "Need to reinstall the Sync Manager? Click here" link
4. Make sure something downloads
> Change QBD Sync Manager back to old version

- __tests__/GithubUtils-test.js
- lib/GithubUtils.js
- package-lock.json
- package.json
@roryabraham will you please review this?
I added the class GithubUtils and its method generateVersionComparisonURL.
I installed the following missing packages 'semver' and '@actions/core'.
PS: Also for the tests I needed to use async/await else I got some timeout. Also I tried different workaround for example expect(Promise).resolves.toBe(url) but it was not working correctly. At least with async/await we are sure the tests are working correctly.
$ https://github.com/Expensify/Expensify.cash/issues/1577
For repository with the following tags 2.2.2, 2.2.1, 2.1.0-1, 2.1.0, 2.0.0-1, 2.0.0, 1.2.2-2, 1.2.2-1, 1.2.2, 1.2.1, 1.2.0, 1.1.0, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0 and 0.0.1
MAJOR comparison
-- if we pass the tag 2.2.2 as …
> Add GithubUtils and generateVersionComparisonURL

- __tests__/GitUtils-test.js
- lib/GitUtils.jsx
@roryabraham @arielgreen will you please review this?
Added GitUtils class and implemented getPullRequestsMergedBetween with unit tests.
$ https://github.com/Expensify/Expensify.cash/issues/1576
I added unit test for `getPullRequestNumberFromCommitMessage` function
I manually executed following command and got expected result.
https://github.com/tugbadogan/expensify-common/blob/37f21ea035930a80282822f3dea6cd25e502d70b/index.js#L61-L67
> Implement getPullRequestsMergedBetween function

- __tests__/GithubUtils-test.js
- lib/GithubUtils.js
@roryabraham will you please review this?
cc @AndrewGable 
This PR updates `generateVersionComparisonURL` to check the build number in the version. I've also updated the tests to cover more version comparison cases. Once this is merged I'll update the expensify-common hashes in all the other repos.
Related to https://github.com/Expensify/Expensify/issues/156562
Added automated tests
N/A, we'll fully test this when we deploy
> Update versionComparisonURL to check build versions

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.js
@timszot can you review this please? I'm not 100% sure this is the way we want to do `code` tags inside of links
Fixes latest two broken links in https://github.com/Expensify/Expensify/issues/153365
1. Automated
1. Manually applied these changes to expensify.cash
2. sent the following message
```
[test `[test](google.com)`](google.com)
https://www.upwork.com/jobs/~016781e062ce860b84
```
3. Verified it linked properly
> Add link inside of link support and fix upwork links

- .github/workflows/cla.yml
Updates our CLA bot to not lock pull requests are merged, I asked them to implement this feature for us and they did! 🥳 
https://github.com/cla-assistant/github-action/issues/77
https://github.com/cla-assistant/github-action/pull/78
Fixes https://github.com/cla-assistant/github-action/issues/77
1. I will test in https://github.com/Expensify/Expensify.cash/pull/1998
> Update CLA to not lock pull requests after merge

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.js
cc @timszot 
Regex updates for 
https://github.com/Expensify/Expensify/issues/156476
https://github.com/Expensify/Expensify/issues/153365
1. New automated tests
2. Applied changes to e.cash locally, verified both cases worked
Will be qa'd in the follow up e.cash pr
> Update expensimark for italic code blocks and links with @ in them

- lib/ExpensiMark.js
cc @timszot 
No issue, mobile was borked
1. Automated tests
2. Verified app did not crash when changes were applied to mobile and e.cash
N/a
> Don't use any lookbehinds in inline code blocks

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.js
Please review @Beamanator 
Details of the issue can be found here https://github.com/Expensify/Expensify.cash/issues/1656
Explanation of the solution can be found in https://github.com/Expensify/Expensify.cash/issues/1656#issuecomment-816339424 and https://github.com/Expensify/Expensify.cash/issues/1656#issuecomment-816905209 comments.
$ https://github.com/Expensify/Expensify.cash/issues/1656
1. What unit/integration tests cover your change? What auto QA tests cover your change?
I have added more tests to support the logic here.
2. What tests did you perform that validates your changes worked?
I have run the unit tests over the codebase which passed.
- You can run the unit test and see if they passed. 
- Or, You can use the latest …
> Fix end parenthesis issue with urls in ExpensiMark

- __tests__/Str-test.js
- lib/str.js
@roryabraham will you please review this?
cc @tgolen
The way we were using `htmlDecode` in place of `stripHTML` was wrong I believe. Strip means to remove. In any case, the implementation of `htmlDecode` was not actually stripping tags in the first place:
```
>> Str.stripHTML('<strong>hello</strong>')
"<strong>hello</strong>"
>> $('<textarea/>').html('<strong>hello</strong>').text();
"<strong>hello</strong>"
```
None, but using to clean up code mentioned here: https://github.com/Expensify/Expensify.cash/pull/2320/files#r613669999
- Added Unit tests
> Update stripHTML to actually strip tags

- lib/CONST.jsx
We need to add a new public domain for cheerful.com which seems to be linked to mail.com accounts. 
https://github.com/Expensify/Expensify/issues/161789
N/A
N/A
> Adding cheerful.com as public domain

- lib/str.js
@MonilBhavsar will you please review this?
cc @roryabraham @Beamanator 
This PR adds a new function for checking if an email is a domain email to be used in E.cash for [this issue](https://github.com/Expensify/Expensify.cash/issues/2441) and for any future uses. This can also replace the [domainUtils](https://github.com/Expensify/Web-Expensify/blob/master/site/lib/domainUtils.js#L291) function in Web-E so the implementation is in one place.
Related to https://github.com/Expensify/Expensify.cash/issues/2441
1. Inside the expensify-common directory, I ran `npm link` while on this branch
2. I checked out Web-Expensify master and ran `npm link expensify-common`
3. I ran `grunt watch` in Web-Expensify, and went to `expensify.com.dev` and confirmed that `Str.isDomainEmail` worked in the JS …
> Add isDomainEmail function to str lib

- lib/CONST.jsx
Add claconnect.com to public domains
$ https://github.com/Expensify/Expensify/issues/163835
> add claconnect.com as a public domain

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.js
@bondydaa My local Android build for E.cash is broken. If yours has been working, do you mind copying [the changes](https://github.com/Expensify/expensify-common/pull/376) from `ExpensiMark.js` to `Expensify.cash/node_modules/expensify-common/lib/ExpensiMark.js`, running it on Android, and following the QA steps just to verify that it works? Should be fine, I just know there might be quirks with the Regex parsers for Android.
Our code fencing previously only worked if there were newlines surrounding the wrapped text. This changes it so that you don't need newlines (just like what Slack offers). See the issue for more context.
e.g:
\```
hi
\```
and \```hi\``` are the same.
$ https://github.com/Expensify/Expensify.cash/issues/3039
- Expensimark-test covers all my changes. I've updated each …
> Allow more lenient code fencing with new lines

- .github/workflows/cla.yml
I noticed that dependabot couldn't pass the CLA in this repo, so I added an allowlist.
Example: https://github.com/Expensify/expensify-common/pull/377
N/A
N/A
> [No QA] Added dependabot to the allowlist for CLA

- lib/CONST.jsx
Reverts Expensify/expensify-common#369
for https://github.com/Expensify/Expensify/issues/164401
> Revert "add claconnect.com as a public domain"

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.js
@roryabraham @jasperhuangg @marcaaron  will you please review this?
Context: https://github.com/Expensify/Expensify.cash/issues/2847
**What unit/integration tests cover your change? What autoQA tests cover your change?**
Yes I have added tests
**What tests did you perform that validates your changed worked?**
Yes
**What does QA need to do to validate your changes?**
Try various HTML strings with `<br>` tags in various combinations
HTML -> MD
1. `Hello<br/>There` -> `Hello\nThere`
2. `Hello<br></br>There` -> `Hello\nThere`
Tests -> https://github.com/Expensify/expensify-common/pull/381/files#diff-7031bf36a0d060dfeb1742c45b8fa6853fb5790ef4da366b0fb96ceaafd342ea
**What areas to they need to test for regressions?**
Parser
> feat: HTML to markdown parser

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.js
Created a process to quotes like what is done with `modifyTextForUrlLinks` at [ExpensiMark](https://github.com/Expensify/expensify-common/blob/master/lib/ExpensiMark.js) module having a function to deal with quotes:
https://github.com/Expensify/Expensify.cash/issues/2670
1.  Tested in the chat with these inputs:
```
> This is a one line quote
> This is a two line quote
> And this is the second line
> This is a three line quote
>
> With an empty line in the middle that has no space after the chevron
> This is another three line quote
>  
> But this time there's a space after the middle chevron
```
```
> This is another three-line quote
> 
>
>
> But this time there's a space after the middle chevron
```
1. Type in the keyboard and see that the quote now works correctly
**Android**
> Changes in quotes

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.js
@thienlnam will you please review this?
$ https://github.com/Expensify/Expensify.cash/issues/2846
1. What unit/integration tests cover your change? What auto QA tests cover your change?
I have extended the existing tests to cover the Changes.
Jest test & manual inspection.
a. Try to parse a message which contains any of the Italic, Strikethrough, bold text.
b. Only text containing no space after starting or before ending symbol will be parsed and converted to html.
1. What areas do they need to test for regressions?
1. Test messages on the E.cash app. If they are rendered as expected or not.
> Skip match if there is space after Starting or before ending main symbol in Expensimark [ ~ , _ ,* ] only

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.js
cc @chiragsalian 
$ https://github.com/Expensify/Expensify/issues/167534
1. Send a concierge message to yourself with a multi-level email domain, e.g. `applausetester+qaabecciv@applause.expensifail.com`
2. Open the chat and verify that the copy icon shows after the email.
Tests above.
> Fix copy icon on multi-level domain emails

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
@Jag96 Will you please review this?
1. Added more rules to our ExpensiMark HTML to Markdown parser.
2. Created a Separate text file for HTML to Markdown parser.
3. Added a couple of tests.
$ https://github.com/Expensify/Expensify.cash/issues/3970
Covered with Jest Unit tests
I used the changes here to E.cash repo to try pasting HTML strings in Composer
After these changes are merged to E.cash, you can try copy-pasting formatted String to Composer. Otherwise, add more unit Tests and test them.
1. What areas do they need to …
> New Rules added to HTML to markdown parsing [bold, italic, Strikethrough]

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
@Jag96  will you please review this?
If a `br` tag is followed by a newline then we should parse both as single newline. e.g.
` <b>Joe likes to eat <b><br>\n Apple & Doughnut.`
$ https://github.com/Expensify/Expensify.cash/pull/4009#issuecomment-879534328
UNit
Unit
NA
NA
> Fix newline parsing in MD to HTML parser

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
@Jag96  will you please review this?
$ https://github.com/Expensify/Expensify.cash/issues/4052
Unit
unit
Try to paste a few messages that contains line breaks in E.cash after this is merged.
E.cash.
> Fixed lin-break <br> HTML parsing

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
@Jag96 will you please review this?
Fixed regression https://github.com/Expensify/Expensify.cash/issues/2846#issuecomment-881660905
Added more Unit test
I tested various strings 
Send a message with single char in E.cash after this code is merged.
1. What areas do they need to test for regressions?
E.cash app
> Fix: single char match in ExpensiMark

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
Anyone, will you please review this?
We escape the input string before apply Rules from Expensimark but we forgot to check for the Escaped chars in the URL regex. I have updated that.
Apart from it, Added `:` to the regex so that it can be matched as part of the URL. Google Map URLs contain this.
$ https://github.com/Expensify/App/issues/4105
Unit test
I tried many URLs for matching and all seem to pass 
URLs should be parsed in E.cash.
E.cash messaging
> fixed url parsing for escaped chars

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
@stitesExpensify will you please review this updated PR?
- Updated the regex for handling characters between [] for the hyperlink.
$ Fixes: [Expensify/App#4229](https://github.com/Expensify/App/issues/4229)
1. "Test markdown and URL links with inconsistent starting and closing parens" covers testing of the given changes
1. Tested against incorrect pairs, symbols, and special characters handling
1. Test with different string patterns for the URLs  
2. Explore complex strings to validate the regex
2. Regression has to be run for inconsistent parenthesis and links with style
> Fixed characters support between [] for Hyperlinks

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
anyone will you please review this?
https://github.com/Expensify/App/issues/4066#issuecomment-886825068 for https://github.com/Expensify/App/issues/4066
https://github.com/Expensify/App/issues/4169#issuecomment-884508675 for https://github.com/Expensify/App/issues/4169
$ Fixes https://github.com/Expensify/App/issues/4066
$ Fixes https://github.com/Expensify/App/issues/4169
Unit tests added.
Manual text matching.
Message Formatting in New Exepnsify
Message Formatting in New …
> Fix HTML-> MD Conversion

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
Added support for HTML quote parsing in HTML to MD conversion.
1. It first grabs the whole string between `<blockquote>` tags.
2. we divide each new line in the text with `> line text`
3. if line Text is `\n` we skip this char to remove the extra line and conversion would be `> `.
$ https://github.com/Expensify/App/issues/4188
I have added Unit tests that cover cases where Quotes can also contain other HTML tags or newlines.
I used a couple of quoted texts and paste them into the Composer in the E.cash to test my solution. 
1. What …
> Quote support for HTML => MD Conversion 

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
@AndrewGable will you please review this?
Creation of html -> markdown conversion of inlineCodeBlock
[#4185](https://github.com/Expensify/App/issues/4185)
https://user-images.githubusercontent.com/56851391/127571638-4ae748f9-3947-4a00-a6f8-988f7de4d5ae.mp4
Unit test were added to [__tests__/ExpensiMark-Markdown-test.js](https://github.com/Expensify/expensify-common/blob/master/__tests__/ExpensiMark-Markdown-test.js)
1. Enter a message with inline code block
2. Try to edit it
3. Verify it will keep the inline code block markdown
> inlineCodeBlock html -> markdown

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
Added regex rule for code fence HTML to markdown conversion.
$ https://github.com/Expensify/App/issues/4184
I added unit test for this regex rule.
I run E.cash with updated Expensify-common package from this PR.
Copy/pasted sample code pieces from Slack to E.cash.
Used edit feature on E.cash to make sure code fences are converted to markdown properly.
https://user-images.githubusercontent.com/3853003/127780267-88f46d9d-0389-45d9-9d9d-d81bcfab8bf0.mov
Copy/paste code blocks from Slack to E.cash
Edit code block messages and save again.
Make sure …
> Code fence HTML to markdown conversion

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
1. Firstly, it parses the Anchor tags.
2. Now based on found groups in the match. It first picks links that start with `mailto:` and then if text and URL are not the same. It would be converted to Markdown style links `[]()`.
3. At last, if step 2 is not a pass, then it would be a normal link.
I noticed that it's unsafe to unescape the HTML before matching tags. for example, if a tag is escaped then it means it was not HTML and thus I moved the `_.unscape` after all the parsing is done.
$ Fixes https://github.com/Expensify/App/issues/4187
I have a lot of Unit tests.
I used …
> Links support to HTML => MD conversion

- __tests__/Logger-test.js
- lib/Log.jsx
- lib/Logger.jsx
Alright, please give this a review. You can see it being used in the draft PRs tied to the issue.
I basically revamped how the logging class works, mainly:
- All logs are saved in a queue
- alert, warn and hmmm automatically flush the queue to the server (this is basically unchanged)
- info can chose to flush or not (this is basically unchanged)
- Whenever we flush the queue, we flush it all
- I removed the "extraneous" recentMessages params from alert, warn, hmmm since now they will always flush the entire queue
- Made it so that each queue flush includes the previous queue flush requestID so you can go to the past events of one flush
This is an example of what we log in App (there's 2 requests there to see the previous requestID thingy):
```
2021-07-23T16:53:45.731933+00:00 …
```
> Improve Logger class

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
@tgolen  will you please review this?
Updated markdown regex to avoid nested cases
$ [Expensify/App](https://github.com/Expensify/App/issues/4526)
1. Test url replacements
2. Test markdown style link with various styles
3. Test critical markdown style links
4. Test markdown and url links with inconsistent starting and closing parens
> Fix MD Hyperlink Regex for nested cases

- lib/CONST.jsx
Related to https://github.com/Expensify/Web-Expensify/pull/31774
cc: @thienlnam 
$ https://github.com/Expensify/Expensify/issues/174490
NA
No QA
> [No QA] Update email constants for EXPENSIFY_EMAILS and INVALID_SUBMIT_EMAILS to match Web-E

- lib/ExpensiMark.js
- lib/components/form/element/combobox.js
- lib/components/form/element/dropdownItem.js
- lib/components/form/element/switch.js
- lib/jquery.expensifyIframify.js
- package-lock.json
- package.json
https://github.com/Expensify/expensify-common/pull/407#issuecomment-902009232
See https://github.com/Expensify/Web-Expensify/pull/31783
> Update to latest version of eslint-config-expensify

- lib/ExpensiMark.js
https://github.com/Expensify/App/issues/4484#issuecomment-903352516
$ https://github.com/Expensify/App/issues/4484
There are existing tests https://github.com/Expensify/expensify-common/blob/e5a22b54cde72ff3b9b6b085ea4374144e8937b2/__tests__/ExpensiMark-Markdown-test.js#L68
I copied-pasted content from Mac Notes.app into our web app in chrome browser where this issue was reported.
Follow the steps on the linked issue.
NewDot.
> fix extra spaces in HTML to markdown

- lib/CONST.jsx
Rename constant that contains list of invalid report approvers/sharees and remove svfg@expensify.com from this blacklist
Part of https://github.com/Expensify/Expensify/issues/175079
Will be covered in the related Web PR: https://github.com/Expensify/Web-Expensify/pull/31805
No QA
> [No QA] Update invalid approver/sharee email list and rename constant

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
@jasperhuangg will you please review this?
Updated the tests and parsers to have rel="noreferrer noopner" and also updated the regex [here](https://github.com/Expensify/expensify-common/blob/7d8408c5c78792394eee8e079f115b1380221a23/lib/ExpensiMark.js#L130) so that it works as it was working before (to prevent the `target="_blank">` section of the link replacement from being captured)
$ https://github.com/Expensify/App/issues/4256
1. Test quotes markdown replacement with text matching inside and outside codefence without spaces
2. Test markdown and url links with inconsistent starting and closing parens'
3. Test a url ending with a closing parentheses autolinks correctly
4. Test a url ending with a question mark autolinks correctly
5. Test a period at the end of a link autolinks correctly …
> update url parsing

- lib/API.jsx
Add a new API call - `Expensiworks_getAgentAccuracy()` to smoothly remove `SSDos_getAgentAccuracy()` [here](https://github.com/Expensify/expensify-common/blob/b5d9167a26cfd40beebdfb79958b3bbed1af7b64/lib/API.jsx#L662)
Part of https://github.com/Expensify/Expensify/issues/177284
Required for https://github.com/Expensify/Web-Expensify/pull/31924
None, will be tested with https://github.com/Expensify/Web-Expensify/pull/31924
No regression, as it just introduces new function that is not invoked …
> Add new API call for fetching agent's accuracy in Expensiworks

- lib/API.jsx
@TomatoToaster will you please review this?
We added a new API call in PR https://github.com/Expensify/expensify-common/pull/418
and updated Web-E to use the updated API method. So we can now safely remove this method
Follow up for https://github.com/Expensify/Expensify/issues/162098
N/A
N/A
> Remove unused API method

- lib/ExpensiMark.js
- lib/components/form/element/combobox.js
We were adding non-matches to searches when `this.props.showDisabledOptionsInResults` was true. This was causing the search to not work for very large policies.
$ https://github.com/Expensify/Expensify/issues/147788
1. Make this change in Web-Expensify 
- i.e. open `./Web-Expensify/node_modules/expensify-common/lib/components/form/element/combobox.js`, apply the diff from this PR, and run `grunt` in `./Web-Expensify`
2. Turn on local js for prod
3. Supportal into ops@kruzeconsulting.com
4. Go to domains -> wellapp.com -> company cards
5. Click "Edit exports" on one of the users
6. Under QBO where it says "Default Card" search for whatever you want
7. Make sure the results actually match what you type
> Fix combobox searching

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
Changing URL regex in order to match when link have a special charactere such as ( . , = ( + $ ! * ) right before a  /
[#6216](https://github.com/Expensify/App/issues/6216)
1. Enter the chat.
2. Type any URL.
3. Verify the URL is autolinked. 
1. Enter the chat any URL(specially with special charactere before a /), it must match with the new regex and be autolinked.
> URL PATH REGEX improved to match any link

- lib/CONST.jsx
I updated the comment to mention that we need to keep this constant up to date in two places now. In both the web-expensify and app repos now that we have new dot. 
I found this while working on https://github.com/Expensify/Expensify/issues/174181. 
No tests, just updated a comment. 
No QA, just updated a comment.
> Update comment on EXPENSIFY_EMAILS constant to mention new dot

- lib/str.js
@roryabraham will you please review this?
Invoking scripts through Chrome dev tools causes the code here to mistakenly assume that `$` is `jQuery` 
`$` is Chrome's command line API when the dev console is running
SO high ranking answer on the matter: https://stackoverflow.com/a/6973954/4834103
$ n/a
Existing unit tests covering `Str.htmlDecode` in `ExpensiMark-Markdown-test.js` still pass...
I've tested my changes using `npm link` and Expensify/App
- This used to cause an error
n/a
> str: htmlDecode/Encode update jQuery check and usage

- lib/components/form/element/combobox.js
Saves current value when user tabs out of the `To` field.
$ https://github.com/Expensify/Expensify/issues/186694
Will be tested once Web-E PR is merged. But here are some testing steps for Web-E:
1. Open the Reports page and click on a report.
2. Click on `Send` and enter a value in the `To` field.
3. Tab out of the input and verify that the value remains.
Additionally, I tested a lot of other usages of `React.c.FormElementCombobox` and they worked as expected.
No QA.
> [No QA] Fix tabbing out of "To" field in "reports send dropdown"

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
@puneetlath @rushatgabhane will you please review this?
This change is made to solve the issue "Saving without editing the multiline comments edit box shows [Comment Deleted] in LHN"
**Reason:**
In editReportComment in Report.js, we are using ExpensiMark as the parser and ExpensiMark uses `<br>` as the line break. But the originalReportAction.message[0].html has `<br />` as the line break. So, two messages when compared appear different and it is considered to be edited. So, though the message is not edited, the message is indicated as an edited message. Problem begins here.
$ https://github.com/Expensify/App/issues/7268
1. Send multiline message.
2. Click on edit to edit the message. Save without editing
3. Nothing happens to lastMessageText in LHN. Previously, lastMessageText was …
> Changed <br> to <br /> as line break to solve the issue "Saving without editing the multiline comments edit box shows [Comment Deleted] in LHN"

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
@Beamanator @rushatgabhane will you please review this?
Code block is wrapped by `<pre>` `</pre>` tags. And When new line is added `<br />` tag is also added. So, In turn, `</pre> <br />` tags get added in the html. 
Here, `</pre>` tag changes the line and `<br />` add another line. So there is extra line. 
$ https://github.com/Expensify/App/issues/7496
1. Send some code blocks in chat like
Here is come code
```
const myLineOfCode = 'some code';
```
And that was my code!
2. There should not be an extra line below the codeblock.
1. Send some code blocks in chat like
Here is come code
```
const myLineOfCode = 'some code';
```
And that was my code!
2. There should not be an extra line below the codeblock.
> Remove extra line under codeblock

- lib/components/form/element/combobox.js
Underscore's `uniq` function is slow as **** in comparison with lodash's `uniqBy`. This performance issue was causing the browser to freeze when used on a big array (205141 elements in this case)
Doing tests locally, `underscore.uniq` just freezes, don't know how long it really takes, meanwhile, `lodash.uniqBy` returns in around 200 ms
$ https://github.com/Expensify/Expensify/issues/204905
1. Do the same changes this PR is doing in `node_modules/expensify-common/lib/components/form/element/combobox.js` (Web-E)
2. Use `grunt watch` to rebuild everything
3. Use this [SO](https://stackoverflow.com/c/expensify/questions/29) to use your local JS in production
4. Follow the QA Steps
1. Supportal into accounting@alayacare.com
5. Type something in this combobox to filter the results:
6. Should …
> Replace underscore.uniq by lodash.uniqBy for performance

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
- lib/components/StepProgressBar.js
- lib/components/form/element/combobox.js
- lib/components/form/element/dropdown.js
- lib/components/form/element/dropdownItem.js
- lib/components/form/element/switch.js
- lib/jquery.expensifyIframify.js
- lib/mixins/extraClasses.js
- lib/mixins/validationClasses.js
- lib/str.js
@roryabraham @rushatgabhane  @iwiznia will you please review this?
fix mapping the block to newline (div,comment, h tags)
fix map table to a new line. 
the proposal for these 2 issues is here : 
https://github.com/Expensify/App/issues/7352#issuecomment-1064853399
https://github.com/Expensify/App/issues/7644#issuecomment-1078958732
$ https://github.com/Expensify/App/issues/7352
$ https://github.com/Expensify/App/issues/7644
change this https://github.com/Expensify/expensify-common/pull/436#discussion_r834056874
use the cases I add on UT …
> fix  new line issue 

- __tests__/ExpensiMark-FlatText-test.js
- __tests__/ExpensiMark-HTMLToText-test.js
- lib/ExpensiMark.js
@parasharrajat @Luke9389  will you please review this?
I'm adding a new function to replace the HTML report message that use for showing text on LHN.
$ https://github.com/Expensify/App/issues/8134
`__tests__/ExpensiMark-FlatText-test.js`
```
> Confusing stuff
Tell me about it
```
Type above text and should be converted to text `Confusing stuff Tell me about it`
Verify that `__tests__/ExpensiMark-FlatText-test.js` is pass.
The function created is used on showing the …
> convert html to flat text for LHN uses

- lib/CONST.jsx
Update the constant used to download the QBD Sync Manager, which has been updated to a new version. The new installer was already uploaded to static [here](https://github.com/Expensify/Web-Static/pull/100). 
Part of https://github.com/Expensify/Expensify/issues/209252
This will be tested and QAed when we update Web-E to use the new expensify-common version.
> Update QBD Sync Manager filename to new version

- lib/str.js
- package-lock.json
- package.json
$ https://github.com/Expensify/App/pull/8896#issuecomment-1130401493
Can be tested in connection with -> https://github.com/Expensify/App/pull/9060
No QA
> [No QA] Add polyfill for `replaceAll()` to fix Safari iOS 13

- lib/components/form/element/combobox.js
The comparation to selected was not taking into account lower cases inserted by the user.
It should
$ https://github.com/Expensify/Expensify/issues/208426
1. Create an expense (New Expense)
1. Edit the currency
2. Write lowercase `usd`
3. verify that the USD $ choice gets checkmarked
2. Write uppercase `USD`
3. verify that the USD $ choice gets checkmarked
4. Try the same with another currency of your choice
Same as Tests
> Afonseca fix lowercase selected combo

- README.md
We need to run `npm install` so `package-lock.json` is updated, and the acual library is updated, the PR created warns you when it's not run, but I think we should update the readme as well.
https://github.com/Expensify/Expensify/issues/217472
N/A
N/A
> Add the need to run `npm install` so `package-lock.json`

- lib/components/form/element/combobox.js
Clicking an option that doesn't exist when  `allowAnyValue = true` doesn't stick.
$ https://github.com/Expensify/Expensify/issues/215741
1. Checkout this PR: https://github.com/Expensify/Web-Expensify/pull/34070
1. Go to expenses page
2. Type an option that doesn't exist in the Tag filter
3. Click the option appearing with the text you typed
4. Check that the dropdown closes and the input still has the text you typed
2. Type another option that doesn't exist in the Tag filter
3. Press Enter key
5. Check that the dropdown closes and the input still has the text you typed
> Fix combobox click non existing value

- lib/PubSub.jsx
Found [here](https://github.com/Expensify/Expensify/issues/218385#issuecomment-1181677243) that we were getting an empty `eventID` passed in, causing an error that didn't allow merging receipts via the "Attach" paper clip icon
Also replaced `substr` with `substring` b/c `substr` is deprecated (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr)
$ Related to https://github.com/Expensify/Expensify/issues/218385
1. Open a report
2. Add 2 very similar expenses
3. In the report, click "Details"
4. Click "Edit Expenses"
5. Edit one expense by clicking the pencil icon when hovering over an expense
6. Click "Merge" when looking at the expense
7. At this point you'll probably see a pretty empty dialog box (this error is being resolved in another PR)
8. …
> Prevent failing to merge expenses

- lib/components/form/element/combobox.js
Explanation of change:
Changing the report an expense is attached to by typing it in causes an error because we check for capitalization. Removed that check.
Fixes this issue:
$ https://github.com/Expensify/Expensify/issues/218805
1. Open old dot
2. Navigate to the reports tab
3. Create a report titled "abc"
4. Navigate to the expenses tab
5. Click on an expense that is in the open category
6. Clear the report field
7. Type in "a"
8. Ensure that the letter populates and no error appears in the js console.
Same as Tests
> draft pr - removed capitalizing

- lib/ExpensiMark.js
@rushatgabhane @sketchydroide 
- There was no way to write ~~~~ in our current code block. After fixing the markdown issue user can now write ~~~~.
$ https://github.com/Expensify/App/issues/9826
- No changes are need to be done in this test.
- Tested with `npm run test`.
- Go to any chat -> then try writing ~~~~ and send in message the text should remain same without any striked out text.
- First message contains old code and unexpected output. And second message contains expected …
> Markdown issue resolved

- lib/ExpensiMark.js
@rushatgabhane @chiragsalian will you please review this?
https://github.com/Expensify/App/issues/9822#issuecomment-1239426453
This was original proposal but I updated logic below because some browsers (i.e. safari) do not support negative lookbehind 
regex (`?<!`) (details here: https://javascript.info/regexp-lookahead-lookbehind)
Updated logic:
- update regex to still validate true if `<pre>` or `<code>` or `<a>` exists as a prefix (if not exist, of course validated as before)
- In `replacement` callback, if prefix is `<pre>` or `<code>` or `<a>`, don't convert considering as not `bold`. If not, consider as `bold` and convert as before
So actually the idea is same as original proposal
$ https://github.com/Expensify/App/issues/9822
2. In the chat input, enter some text …
> handle asterisk (*) after backtick (`)

- lib/CONST.jsx
Update the constant used to download the QBD Sync Manager, which has been updated to a new version. The new installer was already uploaded to static [here](https://github.com/Expensify/Web-Static/pull/117). 
Part of https://github.com/Expensify/Expensify/issues/231991
This will be tested and QAed when we update Web-E to use the new expensify-common version.
> Update QBD Sync Manager installer filename

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
Part of [this DesignDoc](https://docs.google.com/document/d/1YJmMi9NjnstCAP2Ibo_IZdT2T16Res2jdhWr2WSrk50).
Adds support for heading markdown. A line which starts with # and a space (`# `) is wrapped with `<h1></h1>` tag.
https://github.com/Expensify/Expensify/issues/225615
- there are 2 new automated tests added which checks that markdown is replaced with html tags and vice versa.
- Link the `expensify-common` local repository by following [these steps](https://docs.google.com/document/d/1YJmMi9NjnstCAP2Ibo_IZdT2T16Res2jdhWr2WSrk50)
- Run the app
- Open any chat and send a text message containing lines starting with a # and a space and …
> Add h1 markdown

- lib/API.jsx
Passing `email` as the cardholder's email instead of the logged-in user's email breaks the logging for this request.
https://github.com/Expensify/Expensify/issues/232931
> Allow new param, don't require old param.

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
@rushatgabhane @neil-marcellini will you please review this?
https://github.com/Expensify/expensify-common/blob/805a4c34debc7e27b14e33847ac4df4d59b6d878/lib/ExpensiMark.js#L68-L92
```diff
-                   return `<a href="${g3 && g3.includes('http') ? '' : 'https://'}${g2}" target="_blank" rel="noreferrer noopener">${g1}</a>`;
+                   return `<a href="${g3 && g3.includes('http') ? '' : 'https://'}${g2}" target="_blank" rel="noreferrer noopener">${g1.trim()}</a>`;
```
$ https://github.com/Expensify/App/issues/12511
1. Login with any account
2. Go to any chat room
3. Send a link on markdown with trailing spaces for its URL title (for example, `[  test    ](google.com)`)
4. Verify that URL title is trimmed (for example, [test](google.com))
1. Login with any account
2. Go to …
> trim link title when convert markdown to html

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
`<h1>` tags break the line anyway, there is no need to add a `<br />` when converting `#` markdown to html. This is needed to make header1 look nicer.
https://github.com/Expensify/Expensify/issues/238874
- there are automated tests added which check that the markdown converts to html as expected.
- Link the `expensify-common` local repository by following [these steps](https://docs.google.com/document/d/1YJmMi9NjnstCAP2Ibo_IZdT2T16Res2jdhWr2WSrk50)
- Run the app
- Open any chat and send a custom subject message like following:
`# Custom subject`
`The message body`
- Check that there is no empty lines between the header and the message …
> Avoid duplicate empty line when converting header1 markdown to html

- .github/PULL_REQUEST_TEMPLATE.md
Removes this
```
```
None, I just noticed this is outdated while submitting this PR https://github.com/Expensify/expensify-common/pull/476
None
None
> Remove tag on the first line of PR template

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
https://github.com/Expensify/App/issues/13405
1. Automated test added
2. Installed this on App
3. Sent a message with a link with two underscores `[_example link_](https://www.facebook.com/hashtag/__main/?__eep__=6)`
4. _Verified_ the underscores were not replaced
1. N/a, part of the version bump prs
> Also filter out _blank with a negative look ahead to avoid em in links

- lib/ExpensiMark.js
cc @stitesExpensify 
There's a bit of duplicate code, but I thought this was better than an if/else where link and email handling share the code. I can be convinced otherwise, though
$ https://github.com/Expensify/App/issues/13423
1. Log into your account in NewDot and open a chat
2. Send `[my *web*](www.google.es)`
3. Confirm the word `web` is bold
4. Send `[my *email*](alberto@expensify.com)`
5. Confirm `email` is bold
6. Send `*[my email](alberto@expensify.com)*`
7. Confirm `my email` is bold
Same as tests
> Correctly apply styles to email links

- lib/API.jsx
cc: @johnmlee101 
With our new authentication logic we don't always send passwords across when signing in, so remove that param as a requirement. 
$ Tied to https://github.com/Expensify/Expensify/issues/249359
Tested in https://github.com/Expensify/Web-Expensify/pull/35889
Tested in https://github.com/Expensify/Web-Expensify/pull/35889
> Don't require password as a param for SignIn

- lib/ExpensiMark.js
$ https://github.com/Expensify/Expensify/issues/248976
1. From newdot, send a message in a chat including an email address with numbers and dashes in the domain, like `alberto@exp3nsi-fy1.com`
2. Confirm it is displayed as a mailto link:
3. Now, do the same as a markup link: `[email](alberto@exp3nsi-fy1.com)`. 
4. Confirm it displays as a mailto link:
Same as tests
> Allow numbers and dash in domain names

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
In App we want to be able to send multi-line Markdown comments with **bold** or ~strikethrough~ style. Currently, only strikethrough works to send a multi-line comment, and neither works when editing the comment. I have added tests for both styles and I have updated the regexes (regi? 😂 ) to make all the tests pass.
I made the bold Markdown to html regex very similar to the one for strikethrough. Hopefully I didn't break any untested features in that process. Next, I modified the html to Markdown regexes to match everything inside the tags including whitespace.
@parasharrajat, @aimane-chnaif, @marcaaron I would love to have your eyes on this as well so I don't break anything.
$ https://github.com/Expensify/App/issues/13727
1. What unit/integration tests cover your change? What autoQA …
> Parse multi-line bold and strikethrough markdown

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
Updates the regex that looks for backticks to convert to `<pre>` tags in newDot chats. This change fixes the behavior for more than three backticks in a row. You can see the adjustments [here](https://github.com/Expensify/App/issues/14030#issuecomment-1375783961)
$ https://github.com/Expensify/App/issues/14030
1. Checked in the App, as well as separately, to make sure the new regex appropriately converted chats with backticks into html, both old and new patterns.
1. Open any chat in App
3. Send four backticks, a new line, and four more backticks.
4. No error should appear, sent chat should resemble:
```
`
`
```
> Update CodeFence Regex to allow more edge case backticks

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/14060
1. Login with any account and go to any chat room
2. Send this message:
```
[multiline
text](https://google.com/)
```
3. Edit this message
1. Login with any account and go to any chat room
2. Send this message:
```
[multiline
text](https://google.com/)
```
3. Edit this message
4. Verify that when editing, the original message should be auto-filled
```
[multiline
text](https://google.com/)
```
> Fix/14060: Bug: Link with multiline text loses markdown when edited

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/14694
The change updates the tests in `ExpensiMark-HTML-test.js`, which depended on the previous incorrect behavior (i.e., the line break was always stripped). It also introduces a new test in `ExpensiMark-Markdown-test.js`, which validates the behavior described in the test, which was not covered by existing tests.
1. Add a comment:
````
```
text
```
````
2. Verify that it has an empty line below `text` once added.
3. Edit it and check that it looks the same as 1.
4. Repeat 1-3 for the below, …
> Preserve code fence line breaks and ensure backticks occupy a separate line

- __tests__/ExpensiMark-HTMLToText-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/14670
Proposal: https://github.com/Expensify/App/issues/14670#issuecomment-1413011449
The change updates the tests in `ExpensiMark-HTMLToText-test.js`. The new tests cover "Test new line replacement on heading" and "Test new line replacement on preformatted text" cases (Similiar to what was implemented "Test new line replacement on blockquote").
1. Open the app 
2. Turn off the internet (because the solution has just been implemented in front-end side)
3. Open any chat
4. Send bold text using # …
> Fix/14670 sending multiline messages with 1st line as h1 and 2nd line regular, both lines appears in the LHN

- lib/components/form/element/combobox.js
Part of https://github.com/Expensify/Expensify/issues/260640
1. Add this tag to a policy: `Corporate : OOO Cost Center`
2. Create an expense with that tag
3. Open up the expense to edit it from the expenses page
4. Verify that the name of the tag doesn't have a backslash in front of the colon and verify that the tag field is not red (which would indicate the tag couldn't be found in the policy)
Same as above
> Fix incorrect text being displayed when an option exists

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/14668
1. Open a chat and send this message
```text
```
2. Edit the sent message and verify it's displayed in one line in editing mode
3. Edit and change the sent message to
```text
```
and save it
4. Verify the edited header bold text is still displayed in one line
Same as above tests
Video demo
https://user-images.githubusercontent.com/117511920/218988451-5acc3f56-8e9f-4f45-89e5-734b293436ca.mov
> fix line break handling for HTML h1 to markdown conversion

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
@neil-marcellini @eVoloshchak please take a look.
Markdown symbols like `*text*`, `~text~` or `_text_` should match text with newlines.
Bold and strikethrough markdown have been fixed here https://github.com/Expensify/expensify-common/pull/486
this PR adds fix for italic text `_text_` and corresponding tests
$ https://github.com/Expensify/App/issues/14675
```
npm test -- __tests__/ExpensiMark-HTML-test.js
```
```
npm test -- __tests__/ExpensiMark-Markdown-test.js
```
tested on native and web
<details>
<summary>ios</summary>
</details>
<details>
<summary>ios web</summary>
</details>
<details>
<summary>android</summary>
</details>
<details> …
> Fixes italic markdown to match newline and adds tests

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
Reviewers: @thesahindia @NikkiWines
$ https://github.com/Expensify/App/issues/14695
The tests below are in `ExpensiMark-HTML-test.js`:
- Test covering new changes:
- `Test markdown replacement for emails wrapped in bold/strikethrough/italic in multi-line`
- Tests covering current behavior:
- `Test markdown replacement for emails wrapped in bold/strikethrough/italic in a single line`
- `Test markdown replacement for emails containing bold/strikethrough/italic`
Same as QA.
1. Add the below as a new comment (paste as plain text):
```
~abc@gmail.com
def@gmail.com~
_abc@gmail.com …
```
> Strip ~_* from multi-line auto-emails

- lib/ExpensiMark.js
https://github.com/Expensify/App/issues/15372
- Follow [the steps](https://github.com/Expensify/expensify-common) to get the changes in your App
- Open Newdot and start a chat
- Write `# Hello`. Hello should get formatted as a header
- Write `#  Hello` (with two spaces). Hello should get formatted as a header
- Write 
```
Hello
```
(with two spaces after the #). Hello should NOT get formatted as a header and the `#` should remain visible
Will be QAed with App counterpart
> Ignore heading markup if the line is just whitespaces

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
@aimane-chnaif @deetergp 
$ https://github.com/Expensify/App/issues/15302
1. Send this markdown: ```\n\n# test\n\n``` as new message
````
```
```
````
2. Verify that converted html is `<pre><br />#&#32;test<br /><br /></pre>`
3. Edit this message
4. Verity that converted markdown is ```\n\n# test\n\n``` which is same as original one in Step 1.
5. Add one more line break at the beginning - ```\n\n\n# test\n\n``` and update message
````
```
```
````
6. Verify that converted html is `<pre><br /><br />#&#32;test<br /><br /></pre>`
7. Edit this message
8. Verity that converted markdown is ```\n\n\n# test\n\n``` which is same as original one in Step 5.
Same as Tests step
https://user-images.githubusercontent.com/108292595/225628295-6b7f5b5a-b1dd-4612-8d00-b4840f65084a.mov
> fix codeFence linebreak missing when convert to markdown

- __tests__/Str-test.js
- lib/str.js
We are working on a [P.R.](https://github.com/Expensify/App/pull/16031) to allow the `webp` attachment extension in newDot, but the image preview will only work if `Str.isImage` is truthy for that file extension.
https://github.com/Expensify/App/issues/15565
I updated the `Str-test` tests + this will be tested in https://github.com/Expensify/App/pull/16031
N/A, will be QA'ed in https://github.com/Expensify/App/pull/16031
> Allow `webp` extension in Str.isImage

- lib/CONST.jsx
https://github.com/Expensify/Expensify/issues/272561
This is just a constant change. To confirm it works, I made sure that I'm able to download the sync manager from: https://d2k5nsl2zxldvw.cloudfront.net/files/quickbooksdesktop/Expensify_QuickBooksDesktop_Setup_230317395.exe
No QA. The QA will happen in the follow-up Web PR.
> Update constant to point to new QBD sync manager file

- lib/CONST.jsx
Reverts Expensify/expensify-common#515
As discussed [here](https://github.com/Expensify/Expensify/issues/272561#issuecomment-1499679696), we want to keep pointing to the old link for now, so I'm reverting this change. That way if someone else updates expensify-common, we won't accidentally start pointing to the link that we don't want to.
> Revert "Update constant to point to new QBD sync manager file"

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/16475#issuecomment-1492798632
1. Go to a chat and add a new comment, like `test`
2. Edit the comment to replace it with the following link and save it
```
https://www.facebook.com/hashtag/__main/?__eep__=6
```
3. Verify the link text and url are same as the original link
4. Edit the link to remove the link by replacing the link markdown the following original link and save it
```
https://www.facebook.com/hashtag/__main/?__eep__=6
```
5. Verify the link is not autolinked and displayed as text `https://www.facebook.com/hashtag/__main/?__eep__=6`
https://user-images.githubusercontent.com/117511920/232011057-cec36463-f327-4a1e-8b35-a097e3ef889e.mov
Same as Tests
> skip to replace link text if it is a link

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
https://github.com/Expensify/App/issues/17504
1. Go to a chat and send blank quotes, like '> \n>'
2. Verify that '> \n>' is displayed as the original text and no error shown on the comment 
https://user-images.githubusercontent.com/117511920/233407771-e1abb5b3-1174-47d0-b765-ab7a1179fe46.mov
3. Add following comment
```
> 
>quote1 line a
> quote1 line b
> 
test
> 
test
>quote2 line a
> 
> 
>quote2 line b with an empty line above
```
4. Verify blank quote is not translated and all blank rows inside a quote are retained 
https://user-images.githubusercontent.com/117511920/234045882-0577bb1e-7588-45a3-ac1e-4bf7c07359ee.mov
Same as test
> avoid creating empty blockquote tag

- __tests__/ExpensiMark-HTML-test.js
- lib/Url.js
URLs such as `abc-.com` and `-abc.com` were being treated as valid URLs, when in fact domain labels [can't](https://en.wikipedia.org/wiki/Domain_Name_System#cite_ref-rfc3696_28-0:~:text=Labels%20may%20not%20start%20or%20end%20with%20a%20hyphen) start or end in a hyphen.
$ https://github.com/Expensify/App/issues/17591
1. Enter an invalid URL starting or ending in a hyphen (e.g. `abc-.com`) in a message and send
2. The message should not be hyperlinked
Same as above.
> Disallow start and end hyphens in URL regex

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-HTMLToText-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
https://github.com/Expensify/App/issues/17367
1. Send a message, `> # heading`
2. Verify the text is displayed in as header inside the quote
3. Send following message
```
========= test case 1 ========
> [quote] case 1
> # heading
> [quote] case 1
[normal] case 1
[normal] case 1
========= test case 2 ========
> [quote] case 2
> 
> # heading
> 
> [quote] case 2
[normal] case 2
[normal] case 2
```
4. Verify normal heading and heading inside quote have the same line break handling
https://user-images.githubusercontent.com/117511920/234178742-048ea7c0-5e49-47f6-8d82-3f5e78daa8d5.mov
Same as Tests above
> allow heading inside a quote

- __tests__/ExpensiMark-HTML-test.js
- __tests__/Str-test.js
- lib/ExpensiMark.js
- lib/str.js
@puneetlath @mananjadhav
$ https://github.com/Expensify/App/issues/17882
2. Send valid mention e.g. `@john`, `@david`
3. Send @here mention
The user mention should be replaced as <mention-user>mention</mention-user> and the @here should be <mention-here>@here</mention-here>
Same as tests
> [No QA] Add rule to recognize user `@here` mentions

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/17772
1. Go to a chat and add a comment
```
[click google.com *here*](google.com)
```
2. Verify that the text `here` is displayed in bold
Same as test
> Avoid parsing nested link

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
@parasharrajat @francoisl 
$ https://github.com/Expensify/App/issues/18443
1. Go to any chat and add a comment 
```
@google.com google.com
```
2. Verify that the `@google.com` is displayed as plain text and the next `google.com` is displayed as a link.
Same as test
> fix: auto link after email domain not parsed.

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/17998
1. Add a comment
```
========= test case 2 ========
> [quote] case 2
> 
> # heading
> 
> [quote] case 2
[normal] case 2
[normal] case 2
```
2. Verify that there's a line break before and after the heading for both normal header and header inside quote
3. Edit the comment and verify that the markdown is same as the input.
https://github.com/Expensify/expensify-common/assets/117511920/a7bc1689-4d0c-473a-bb45-000317bc7062
Same as test
> Avoid removing break before and after heading

- lib/Url.js
$ [Expensify/App/issues/18564](https://github.com/Expensify/App/issues/18564)
Verify if `~` works in query params
1. Send a valid url
2. Verify that the sent url appears as a valid url(blue and underlined)
3. Verify hovering over the url shows the tooltip in Web and Desktop
4. Verify that Right click (Web and Desktop) or long press (mWeb and native) shows Copy Url to Clipboard context menu
5. Edit the sent url
6. Verify steps 2-4
**Examples:**
```
https://example.com/search?q=foobar~
https://example.com/search?q=~foobar
https://example.com/?~parameter~
https://example.com/?parameter~
https://example.com/?~parameter
```
Same as tests
<details>
https://github.com/Expensify/expensify-common/assets/68777211/6a04f557-43b8-4672-8882-7058119f4ec5 …
> Allow tilde (~) in url parameters

- __tests__/ExpensiMark-HTML-test.js
- lib/CONST.jsx
- lib/ExpensiMark.js
Emoji only is accepted as an anchor text and it doesn't look pleasing to the eye. We don't want emoji-only text to be anchor text for links.
$ https://github.com/Expensify/App/issues/18386
PROPOSAL: https://github.com/Expensify/App/issues/18386#issuecomment-1542063094
To test, we need to update the hash commit of expensify-common package in App repo into `0f363d1eb6731aac34c20a0102822557253ac6a4` like this:
"expensify-common": "git+ssh://git@github.com/expensify/expensifycommon.git#0f363d1eb6731aac34c20a0102822557253ac6a4"
Open any chat and:
1. Put an emoji inside of square brackets "[]" and put a link inside of parenthesis "()"
2. Post the comment
3. Verify emoji text not to be anchor text for links
Open any chat and:
1. Put an emoji inside of square brackets "[]" and put a link inside …
> fix: emoji anchor text with hyperlink

- __tests__/ExpensiMark-HTML-test.js
- __tests__/Str-test.js
- lib/ExpensiMark.js
- lib/Url.js
- lib/str.js
This PR adds a new method normalizeWebsiteOfUrl in str.js to format the website of url to lower case. The new method is used in both `link` and `autolink` rule replacement to format the `href` property of an anchor tag. It can also be used in the App codebase when handling edited link.
$ https://github.com/Expensify/App/issues/18514
1. Add a comment
```
Google.com
```
2. Click to edit the comment and verify the domain `google.com` of the url is in lower case in the initial draft, like
```
[Google.com](https://google.com)
```
3. Edit the comment to
```
[Google.com](https://Google.com)
```
and save the comment
4. Verify that the link is unchanged.
https://github.com/Expensify/expensify-common/assets/117511920/0856a371-419a-478d-8442-bd01e12ba5cd
N/A
> Add method normalizeWebsiteOfUrl to format the website of url to lower case

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.js
Added `_.unescape` to `htmlToText` method, because we are escaping in `replace`
$ https://github.com/Expensify/App/issues/17658
In `Expensimark-test.js` file, text named `Test text is unescaped`
Checked if string is unescaped and character codes are turning back into characters
Run the new test cases
2. What areas to they need to test for regressions?
Check if character codes are turned back into charecters in `htmlToText` method. `&amp;` ->`&`
> Added unescape to htmlToText

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
- lib/str.js
$ https://github.com/Expensify/App/issues/18983
$ https://github.com/Expensify/App/issues/18857
ExpensiMark-HTML-test.js. Added test for mention inside link and email and update the test with code block/fence a bit.
Make sure mention won't get converted into HTML if it's inside code block/fence and link/email.
Can QA run the unit test? Or maybe we can test in App instead.
In chat by sending mention inside code block/fence and link/email markdown.
Step:
2. Type:
a. Mention inside code block, for example 
```
`hi …
```
> Prevent mention rendered inside link and code

- lib/ExpensiMark.js
- lib/Url.js
$ https://github.com/Expensify/App/issues/18911
ExpensiMark-HTML-test.js. Nothing added because there is no regex change.
Make sure that all unit-tests are passed.
This PR has no regex change. Can verify if all unit-tests are passed.
2. What areas to they need to test for regressions?
Nothing.
> fix: export link regex for use in edit message

- lib/ExpensiMark.js
This PR completely removes `[block]` intermediary as it may coincide with user's input.
$ https://github.com/Expensify/App/issues/17776
$ PROPOSAL: https://github.com/Expensify/App/issues/17776#issuecomment-1538347039
1. Login ND with any account
2. Go to any chat
3. Type the word `[block]` and send it
4. Click the pencil icon to edit the comment
5. Verify that the composer shows `[block]` as is
NA
1. Login ND with any account
2. Go to any chat
3. Type the word `[block]` and send it
4. Click the pencil icon to edit the comment
5. Verify that the composer shows `[block]` as is
<details>
[Screencast from 23-05-2023 21:12:02.webm](https://github.com/Expensify/expensify-common/assets/113963320/91b2d28e-43a8-4e63-aa7e-c092ab0ef4f4)
</details>
<details>
<summary>Mobile …
> Remove `[block]` intermediary

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/19607
1. Go to a chat
2. Add a comment
```
> *This is multiline
bold text*
```
3. Verify that text isn’t bold and the bold syntax is displayed in original text.
https://github.com/Expensify/expensify-common/assets/117511920/14c91e9a-5350-49da-acee-48d67f508d21
Same as test
> Skip rendering bold style when partially overlapping with quote

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/19857
https://github.com/Expensify/expensify-common/assets/117511920/f2a46c8e-0100-4448-8dfc-b35b1bfe9c1d
1. Add a comment `_@here_`
2. Verify that `@here` mention is displayed in italic
Same as test
> Support italic style for @here mention

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.js
Currently `_.unescape()` is used to replace entities while html is being converted to text, however this function only replaces a limited number of entities resulting in only a part of the string being unescaped in a few cases. Because of this I've replaced it with `Str.htmlDecode()`.
For example `&#32;` is not unescaped by `_.unescape()` but is added in the replace function in line 36.
https://github.com/Expensify/expensify-common/blob/925e62744f784a92c3ad8947aabfc21c93bec221/lib/ExpensiMark.js#L23-L39
$ https://github.com/Expensify/App/issues/19789
- Added html entities to the unescape test in `ExpensiMark-test.js`.
- Previously `&amp;&#32;&amp;amp;&#32;&amp;lt;&#32;&lt;` was being unescaped to …
> Use htmlDecode instead of unescape

- lib/str.js
- package-lock.json
- package.json
$ https://github.com/Expensify/App/issues/19790
2. Send an invalid html character, eg: &#50000000;
3. Verify that the app isn't crashed and there's no console error.
Same as Tests.
https://user-images.githubusercontent.com/16502320/241865033-1bf8214e-8d72-4ca0-bce2-4d73a5998e88.mov
> upgrade html-entities version

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/19957
1. Go to a chat and add a comment `@_concierge_@expensify.com`
2. Verify that App doesn’t crash and `_concierge_` is not rendered as italic 
Same as test
> fix: parsing underscores in the email of user mention 

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/20111
1. Go to chat and add a comment
```
h_ello_
```
2. Verify that the comment text is `h_ello_` and it's not rendered as italic style.
Same
> fix: italic syntax removing a preceding character

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/19997
1. Go to a chat and add a comment 
```
[_@username@expensify.com_](expensify.com)
```
2. Verify that the text `@username@expensify.com` of link is not rendered as mention and is italic 
Same as test
> fix: parsing mention wrapped with styles inside link text

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/21234
1. Go to a chat and add following comment
```
[](concierge@expensify.com)
[   ](concierge@expensify.com)
[   
](concierge@expensify.com)
```
2. Verify that 
a. Only emails inside `()` are parsed as email link
b. `[]`, `()` and spaces(including line break) inside `[]` are not parsed
3. Click to edit the comment
4. Verify that the initial draft is same as the original input.
See below demo video 
https://github.com/Expensify/expensify-common/assets/117511920/82b49d50-067b-4299-a3e7-dea2a3ab0928
I'll fill out the full checklist in the PR to update version of App repo.
Same as test
> fix: 'No content to add' error if we send empty alias for email

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/20725
1. Go to a chat and add a comment for case 1
```
==== Case 1: simple quote ===
> one line quote a
> two line quote b
> two line quote b
> quote c with internal line break
> 
> quote c with internal line break
```
2. Open the comment in editing mode and verify that the initial draft is same as input.
3. Select the comment, copy the selection by Ctr/Cmd + C, paste it to composer and verify that it's same as input
https://github.com/Expensify/App/assets/117511920/fa1332d1-b19d-425f-b759-c864b0a0f653
4. Add a comment for case 2
```
==== Case 2: quote surrounded by text ===
text a
> quote a
> quote b
text b
text c
> quote c
text c
```
5. Repeat step 2 and 3
https://github.com/Expensify/App/assets/117511920/b35284f5-3f41-49ef-9223-aa018022d6b3
6. …
> fix: unwanted linebreaks added when translating html blockquote to markdown

- __tests__/ExpensiMark-HTML-test.js
- __tests__/Str-test.js
- lib/CONST.jsx
- lib/ExpensiMark.js
- lib/str.js
$ https://github.com/Expensify/App/issues/20085
1. Login to NewDot
2. Click on any chat
3. Send test@here@gmail.com
4. Send test+1@here@gmail.com
5. Verify the texts as emails are displayed
6. Click on the emails
7. Verify that it opens the mail sender
8. Send @test@gmail.com
9. Send @test+1@gmail.com
10. Verify the texts as mentions are displayed
11. Click on the mentions
12. Verify that it opens the user detail page of the user that was mentioned
1. Login to NewDot
2. Click on any chat
3. Send test@here@gmail.com
4. Send test+1@here@gmail.com
5. Verify the texts as emails are displayed
6. Click on the emails
7. Verify that it opens the mail sender
8. Send @test@gmail.com
9. Send @test+1@gmail.com
10. Verify the texts as mentions are displayed
11. Click on the mentions
12. Verify that it …
> Fix: move autoEmail to before mentions

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/22492
Proposal: https://github.com/Expensify/App/issues/22492#issuecomment-1627450749
1. Go to a chat and add following comment
````
[```code```](google.com)
````
2. Verify that only `code` is displayed as code block and link `google.com` is displayed as auto link.
3. Edit the comment and verify the initial draft is 
````
[```
code
```
]([google.com](https://google.com))
````
Demo video
https://github.com/Expensify/expensify-common/assets/117511920/9fc0302e-cd4c-4195-bb93-f68960acd288
Same as test
> fix: allow to add link with code block inside alias text part

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/22890
Verified that windows-style newline(\r\n) is replaced with `<br />` during the unit-tests
```
Input: 'This sentence has a windows-style newline \r\n Yep just had one \r\n Oh there it is another one'
Output: 'This sentence has a windows-style newline <br /> Yep just had one <br /> Oh there it is another one'
```
Also tested in the following steps
2. Copy any text on windows and paste it to the composer and send it
3. Verify that new line doesn't appear and the text is sent as is
2. Copy any text on windows and paste it to the composer and send it
3. Verify that new line doesn't appear and the text is sent as is
> fix: replace window-style newline with <br />

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.d.ts
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/21266
1. Open iOS App and go to a chat
2. Add following comment
```
www.asjjssjdjdjdjdjdjjeiwiwiwowkdjdjdieikdjfidekjcjdkekejdcjdkeekcjcdidjjcdkekdiccjdkejdjcjxisdjjdkedncicdjejejcckdsijcjdsodjcicdkejdicdjejajasjjssjdjdjdjdjdjjeiwiwiwowkdjdjdieikdjfisjksksjsjssskssjskskssksksksksskdkddkddkdksskskdkdkdksskskskdkdkdkdkekeekdkddenejeodxkdndekkdjddkeemdjxkdenendkdjddekjcjdkekejdcjdkeekcjcdidjjcdkekdiccjdkejdjcjxisdjjdkedncicdjejejcckdsijcjdsodjcicdkejdicdjejajasjjssjdjdjdjdjdjjeiwiwiwowkdjdjdieikdjfidekjcjdkekejdcjdkeekcjcdidjjcdkekdiccjdkejdjcjxisdjjdkedncicdjejejcckdsijcjdsodjcicdkejdi.com
```
3. Verify App doesn’t crash after adding the comment
4. Click to edit the link and replace the link to
``` …
```
> Fix: error from executing url regex

- __tests__/Str-test.js
- lib/CONST.jsx
We don't want the front end to pass emails that are not valid in the backend. We use [FILTER_VALIDATE_EMAIL](https://www.php.net/manual/en/filter.constants.php) from php which validates the emails if they match RFC-822 standards. According to those standards, the username part of the email can't be longer than 64 characters. This PR adds this condition in our regex for the email validation in JS.
See [here](https://expensify.slack.com/archives/C03TQ48KC/p1690482472889119) a discussion about the email validation inconsistency throughout the project.
Part of https://github.com/Expensify/App/issues/23180
1. In NewDot, go to **Profile** -> **Contact Method** -> **New Contact Method**
2. In the email input field add an email with a long username, like …
> Update email regex

- __tests__/Str-test.js
- lib/str.js
$ https://github.com/Expensify/Expensify/issues/303703
Added a unit test for Bs.S, the Venezuelan currency that has a period in the symbol itself. Before, this was parsing as NaN.
In OldDot, Verify that when changing Settings > Policies > Reports > Report Currency to Bs.S then going to Settings > Policies > Expenses > Time and setting the Default Hourly Rate to Bs.S6.00 correctly autosaves.
> Handle currency symbols with a period in fromUSDToNumber

- __tests__/Str-test.js
- lib/str.js
$ https://github.com/Expensify/Expensify/issues/309211
$ https://github.com/Expensify/Expensify/issues/309227
Added two unit tests to test cases without currency symbols and without passing a currency string at all.
Run the QA steps in the linked issues and verify that the error does not occur.
> Handle cases without currency symbols

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/23352
Proposal: https://github.com/Expensify/App/issues/23352#issuecomment-1659859472
1. Go to any chat and Send a text wrapped in two backticks
2. Verify that last backtick is inside of inline code block.
same as test
<details>
https://github.com/Expensify/expensify-common/assets/139204153/ded24e2e-6c23-49af-b25f-796dde4e3619
</details>
<details>
https://github.com/Expensify/expensify-common/assets/139204153/4fefcbf0-df26-41ab-b136-48d496dc3fe5
</details>
<details>
https://github.com/Expensify/expensify-common/assets/139204153/807cda0a-30af-4b7b-9cca-7986024b66ba
</details>
<details> …
> fix: last backtick should be in inline codeblock when sending a text wrapped with two backticks

- __tests__/Str-test.js
- lib/str.js
Reverts
https://github.com/Expensify/expensify-common/pull/561
https://github.com/Expensify/expensify-common/pull/567
https://expensify.slack.com/archives/C05PJA1M5BJ/p1692799880392129?thread_ts=1692741519.031649&cid=C05PJA1M5BJ
> Straight revert of 2 PRs without involving any resolve conflict situation

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/16762
Proposal: https://github.com/Expensify/App/issues/16762#issuecomment-1682687000
Go to a chat and send following test strings and verify that urls and emails are parsed as expected.
<details>
<summary>Test Strings</summary>
```
test@expensify.com https://www.expensify.com
test@expensify.com-https://www.expensify.com
test@expensify.com/https://www.expensify.com
test@expensify.com?https://www.expensify.com
test@expensify.com>https://www.expensify.com
https://staging.new.expensify.com/details/test@expensify.com
staging.new.expensify.com/details
https://www.expensify.com?name=test&email=test@expensify.com
https://staging.new.expensify.com/details?login=testing@gmail.com
staging.new.expensify.com/details?login=testing@gmail.com …
```
> fix: parse deep link correctly

- __tests__/ExpensiMark-HTML-test.js
- lib/Url.js
$ https://github.com/Expensify/App/issues/24367
Proposal: https://github.com/Expensify/App/issues/24367#issuecomment-1686408161
Go to a chat and send following test strings and verify that double quote is not allowed in URL.
<details>
<summary>Test Strings</summary>
```
"om https://www.she.com/"
"om https://www.she.com"
"https://www.she.com/ end"
"https://www.she.com end"
https://www.she.com/path?test="123"
https://www.she.com/path?test="123/"
"https://www.she.com/path?test="123"
"https://www.she.com/path?test="123/"
https://www.she.com/path?test=123"
https://www.she.com/path?test=123/"
https://www.she.com/path?test=/"123"
https://www.she.com/path?test=/"123/"
```
</details>
[Screencast from 13-9-23 07:02:08.webm](https://github.com/Expensify/expensify-common/assets/139204153/fe911bdd-f2d8 …
> double quote not allowed in URL

- lib/CONST.d.ts
- lib/CONST.jsx
This updates the constant in expensify-common to point to the new QBD sync manager file. And adds a new constant for the version number so that we can show the version number in the download link on web. 
https://github.com/Expensify/Expensify/issues/299596
Make sure that you are able to download the file at: https://d2k5nsl2zxldvw.cloudfront.net/files/quickbooksdesktop/Expensify_QuickBooksDesktop_Setup_2300802.exe
Make sure that you are able to download the file at: https://d2k5nsl2zxldvw.cloudfront.net/files/quickbooksdesktop/Expensify_QuickBooksDesktop_Setup_2300802.exe
> Update links to QBD sync manager

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
@robertKozik @cead22 
We end the url at the first unmatched parenthesis because it is unlikely that this closing parenthesis is part of the url and it can be part of the markdown for example
$ https://github.com/Expensify/App/issues/26788
1. Go to any report
2. Send a link with multiple umatched closing parentheses that are not all at the end, for example: `google.com/(toto))titi)`
3. Verify that the link ends at the first unmatched parenthesis, in the above example the link should be `google.com/(toto)`
Same tests and test urls and markdown in general
https://github.com/Expensify/expensify-common/assets/19537677/ff78206c-b5c6-41b3-b519-558eea3a6037
> End the url at the first unmatched closing parenthesis

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
Strikethrough link isn't parsed correctly on link with URL that contains `~`
$ https://github.com/Expensify/App/issues/27329
1. Open a chat
2. Send this message `~[Example Link](https://example.com/?example=~ex)~` (URL includes `~`)
3. The text must be crossed out
Input: `~[Example Link](https://example.com/?example=~ex)~` 
Output: ~[Example Link](https://example.com/?example=~ex)~
1. Open a chat
2. Send this message `~[Example Link](https://example.com/?example=~ex)~` (URL includes `~`)
3. The text must be crossed out
> Strikethrough link is not parsed correctly on link with URL that contains tilde

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/27445
```
Input: <h1>heading1</h1> in the beginning of the line
Output: # heading1\n in the beginning of the line
```
1. Open any chat and send message
```
in the beginning of the line
```
2. Switch the message just sent to edit mode
3. Verify that spaces in the second line not disappeared
1. Open any chat and send message
```
in the beginning of the line
```
2. Switch the message just sent to edit mode
3. Verify that spaces in the second line not disappeared
> fix: keep tail spaces in heading

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/28344
1. Go to a chat and add a link, like `https://staging.new.expensify.com/details`
2. Click the to edit the comment and add an extra parentheses `)` at the end of the link markdown, like
```
[Staging Detail](https://staging.new.expensify.com/details))
```
3. Save the draft
4. Verify link is not removed and the extra ending parentheses is not part of link and is displayed as plain text.
https://github.com/Expensify/expensify-common/assets/117511920/5caa4b3e-165c-4243-8d88-2a57d5dc884b
Same as tests.
> Fix adding parentheses after link removes link

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ GH_LINK https://github.com/Expensify/App/issues/28544
$ Proposal https://github.com/Expensify/App/issues/28544#issuecomment-1741831052
1. Go to any chat on New Expensify
2. In the composer, type a message `[emoji](email)` (for example `[😄](abc@gmail.com)`) and send
3. Verify that in the message sent, emoji is not changed to link
1. Go to any chat on New Expensify
2. In the composer, type a message `[emoji](email)` (for example `[😄](abc@gmail.com)`) and send
3. Verify that in the message sent, emoji is not changed to link
<details>
<summary>Result</summary>
https://github.com/Expensify/expensify-common/assets/102477862/623ed57c-695a-4cb8-a22e-e6dedb3f7edc
</details>
> match email rule with link rule

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/28344
1. Go to a chat and add link like
```
https://www.google.com
```
2. Edit the link from
```
[https://www.google.com](https://www.google.com)
``` 
to
```
https://www.google.com
```
3. Save it and verify that link, `https://www.google.com`, is displayed as plain text
https://github.com/Expensify/expensify-common/assets/117511920/a5bb7a43-7dd2-4496-85df-3f656b06df9e
Same as tests
> Fix edit to remove link not working

- lib/CONST.jsx
[Related issue](https://github.com/Expensify/Web-Expensify/pull/39110#discussion_r1355242371)
$ GH_LINK
Modified locally the `CONST.jsx` file in `node_modules/expensify-common` and ensured `42` was shown in the RHP for someone who has the NVP `private_eligible50` set to `true` on a brand new account that clicked on Business in the first Inbox task. 
- Support login into an account with `private_eligible50` set to `true`
- Click `Business` in the inbox task
- The RHP should open and you should see the number `42`
> Add const MAX_TRIAL_BONUS_DAYS

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/24281
1. Open any report
2. Paste `~```Code```~`
3. Observe the code block text doesn't gets strike through line and code block creates line break before start and after end
1. Open any report
2. Paste `~```Code```~`
3. Observe the code block text doesn't gets strike through line and code block creates line break before start and after end
https://github.com/Expensify/expensify-common/assets/85894871/a3eeae28-204b-4a1a-9c36-034113c4b2d6
> fix: Can strike-through pre code block.

- __tests__/ExpensiMark-HTML-test.js
- lib/CONST.jsx
- lib/ExpensiMark.js
Because we are removing unmatched end parenthesis, some links that end with special characters are accepted when they shouldn't be. we need to remove those special characters.
$ https://github.com/Expensify/App/issues/25532
1. Go to any repórt
2. Send a link with a slash for example: google.com/toto
3. Edit the message and add one of those characters to the link in the parenthese: `$*.+!,=`
4. When you validate the edit verify that the text is white without links like this:
5. Send another message google.com/toto.) or google.com/toto$) for example and verify that the special char before the parenthese is not blue (not included in the link)
Same as above and test links in general
Video for web:
https://github.com/Expensify/expensify-common/assets/19537677/8bd1d2ca-5695-412a-8690-448a46295b4 …
> Removing special chars that are in the end of a url and shouldn't be

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/26942
Proposal: https://github.com/Expensify/App/issues/26942#issuecomment-1744062072
Same as QA step
Same as QA step
1. Go to any chat
2. In composer, send message as following
```
google2
google3](https://www.google.com)
```
3. Verify that the first line ([google1) is parsed as header, and `https://www.google.com` will be parsed as autolink.
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Do not allow to parse link with multiline alias text when header markdown is leading

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-HTMLToText-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
[$ GH_LINK](https://github.com/Expensify/App/issues/26016)
https://github.com/Expensify/App/issues/26016
Open the app
Open any report
Write '@' to trigger mentions
Select any one mention, make any letter of mention as capital and send
Hover on mention to observe that tooltip doesn't display the right display name and avatar
For same mention as step 4 or select different mention and capitalize all letters and send
Observe that now it is not displayed as mention
> Issue-26016 make usermention case insensitive

- lib/Device.d.ts
- lib/Device.jsx
Updating the type to the Device lib output to match our code style before we start using it in TS App
Related to https://github.com/Expensify/App/issues/24877
There are no tests related to this, we will test it with the App PR https://github.com/Expensify/App/pull/27709
In the App PR https://github.com/Expensify/App/pull/27709
> Change device type to CamleCase

- lib/API.jsx
Part of https://github.com/Expensify/Expensify/issues/304890
Tested in https://github.com/Expensify/Web-Expensify/pull/39483
None
> Add methods to create and update admin issued virtual cards

- __tests__/URL-test.js
- lib/Url.js
$ https://github.com/Expensify/App/issues/27080
Proposal: https://github.com/Expensify/App/issues/27080#issuecomment-1763892171
1. Go to any chat.
2. Type the following valid local-style urls and observe that it's parsed
```
valid urls
http://localhost:3000
https://local.url
http://a.b
http://expensify
http://google.com/abcd
http://my.localhost.local-domain
```
3. Type the following invalid local-style urls and observe that it's not parsed
```
invalid urls
localhost:3000
local.url
http://-localhost
http://_
http://_localhost
http://-77.com
http://77-.com
http://my.localhost....local-domain:8080
```
Same as tests step
Same as tests step
<details>
</details>
<details>
</details>
<details> …
> Do not allow starting and ending hyphen in local-style urls

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
Disabled writing @here mentions together with letters and numbers at the end. Now only punctuation characters are acceptable 
$ https://github.com/Expensify/App/issues/31180
1. Open Expensify App
2. Open chat
3. Write "@herex" - it shouldn't be parsed into mention
4. Write "@here!" - it should be parsed into mention like: `@here`!
Same as tests
> Fix bug with characters after @here mention

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/26942
Proposal: https://github.com/Expensify/App/issues/26942#issuecomment-1744062072
Same as QA step
Same as QA step
1. Go to any chat
2. In composer, send message as following
```
google2
google3](https://www.google.com)
```
3. Verify that the first line ([google1) is parsed as header, and `https://www.google.com` will be parsed as autolink.
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Do not allow to parse link with multiline alias text when header markdown is leading- fix regression issues

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
- lib/str.js
$ https://github.com/Expensify/App/issues/21753
Proposal: https://github.com/Expensify/App/issues/21753#issuecomment-1759589159
1. Go to any chat.
2. Type the following cases
```
@test.example+2@gmail.com@here
@here@test.example+2@gmail.com
@test.example+2@gmail.com@test.example+2@gmail.com
@here@here@gmail.com
@here@gmail.com@here
@here@here+1@gmail.com
@here+1@gmail.com@here
```
3. Observe that all the mentions are highlighted as expected.
Same as tests step
Same as tests step
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> fix the issue that inconsistent highlighting occurs when multiple mentions are used without spaces

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.d.ts
- lib/ExpensiMark.js
This PR:
- removes the `replacebr` rule option inside `ExpensiMark.rules`
$ https://github.com/Expensify/App/issues/26490
$ https://github.com/Expensify/App/issues/16982
Unit testing
1. Updated existing tests which are affected by this change to pass
2. Added new unit testing
Testing in the `expensify-app`
1. On your local dev environment of `expensify-app`, open `node_modules/expensify-common/lib/ExpensiMark.js` file
2. Remove `replacebr` rule
3. Run the app and test with the following recordings
Test Strings
````
```
code1
```
text
```
code2
```
````
````
|
```
code
```
````
````
```
code
```
````
````
message1```code```message2
````
````
message1 ``` code ``` message2
````
````
message1
```code```
message2
````
````
message1
``` code ```
message2
````
````
message1
```
code
``` …
```
> Issue 26490 remove replacebr

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
This PR:
- adds new shouldKeepWhitespace flag to the parser.replace function in ExpensiMark, which allows trailing whitespace in blockquotes
- changes quote rule logic when shouldKeepWhitespace is true
- allows trailing whitespace in blockquote in edit mode
- allows leading spaces in blockquote in edit mode
https://github.com/Expensify/expensify-common/assets/39538890/8a4de1fe-c2c4-423f-929e-57728961c01c
$ https://github.com/Expensify/App/issues/31178
$ https://github.com/Expensify/App/issues/31179
$ https://github.com/Expensify/App/issues/31182
To test these changes I've added proper tests connected to all needed behaviors for Live Markdown Preview. To test it by yourself you will need [example app](https://github.com/tomekzaw/MarkdownTextInput/tree/%40Skalakid/expensify-common-fixes). …
> Enhance ExpensiMark blockquote parsing for Live Markdown Preview

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
Removed the `+` quantifier from the `userMentions` regex because this resulted in all the @ signs being matched when a mention had multiple preceding @ signs. 
For example, the match looked like this `@@user@expensify.com`, and clicking it showed a user with `@user@expensify.com` as their email in the RHP. Trying to message this user then resulted in an error because their email address was invalid.
With this change, the match now looks like this: @`@user@expensify.com`, which, upon clicking/tapping, shows the valid email `user@expensify.com` in the RHP, so the user can now be messaged without errors. 
**Please Note:** I've altered the linking below slightly in accordance to this [comment](https://github.com/Expensify/expensify-common/pull/607#issuecomment-1821707573) because doing it …
> Fix/28946 Mentioning an email with double @ sign results in an invalid email mention

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/26941
Proposal: https://github.com/Expensify/App/issues/26941#issuecomment-1850051964
1. Go to any chat.
2. Type the following test strings and observe that it's parsed as expected
```
_test
> test_
*test
> test*
~test
> test~
```
Same as tests step
Same as tests step
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> Do not apply Italic marckdown for multiline-quote message

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
This PR modifies the replacement function for inline code blocks. Now, the function checks if the content consists only of backtick symbols. If yes, the unmodified match string is returned; otherwise, the behavior should remain unchanged.
I opted to implement this check within the replacement function rather than inside the already established regex. This decision was made because incorporating this check inside the regex was challenging without introducing regressions (especially with the ` ``` ``` ` string). Moreover, splitting it should be beneficial for code readability.
$ https://github.com/Expensify/App/issues/31493
two unit test are added to the test suite to cover prime examples of this issue: ` …
> Prevent parsing backticks if are only content of inline code block

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/30823
Proposal: https://github.com/Expensify/App/issues/30823#issuecomment-1792055791
1. Go to any chat.
2. Type the following test strings and observe that it's parsed as expected
```
_test_test_test_
*test*test*test*
~test~test~test~
```
Same as tests step
Same as tests step
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
> fix-#30823: Keep consistency to parse bold/italic/strikethrough markdown

- .github/workflows/lint.yml
- .github/workflows/test.yml
- package-lock.json
While addressing this [issue](https://github.com/Expensify/Expensify/issues/342635) I realized this repo is still not updated to node 20.  
$ https://github.com/Expensify/Expensify/issues/316192
- `npm install`
- `npm ci`
- `rm -rf node_modules && npm install`
- Tested with https://github.com/Expensify/expensify-common?tab=readme-ov-file#testing-your-code-while-you-are-developing
No QA.
> Upgrade node to v20

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.d.ts
- lib/ExpensiMark.js
This PR extends usage of the `shouldKeepWhitespace` flag which was created for Live Markdown Preview. 
- changes the name of the flag to `shouldKeepRawInput` to indicate extended usability of the flag
- based on this flag new replacement method can be called if implemented for every rule.
- new replacement method should return similar HTML structure as normal replacement but enrich the tag with unmodified values of input which is necessary for Live Markdown Preview
- unmodified values are exposed by `rawInputReplacement` functions as new HTML attributes:
- `data-code-raw` - contains escaped version of code block, new lines/whitespaces included
- `data-raw-href` - contains unmodified version of the link/email
- `data-link-variant` - contains information whether the link was typed as …
> Data html attributes

- package-lock.json
- package.json
Updating some versions so sub-dependencies get updated. We can safely update to v29 since it was updated [here](https://github.com/Expensify/App/blob/96cce5dc64ec9836a753dcdbcee5e27920f85e90/package.json#L234) in App.
$ https://github.com/Expensify/Expensify/issues/342635
None.
No QA.
> Update packages for vulnerabilities

- lib/str.js
- package-lock.json
- package.json
This PR removes the String.replaceAll ployfill in an attempt to reduce the bundle size. String.replaceAll method is natively supported from NodeJS v15 onwards. So the polyfill is not needed any more. This removes appoximately 30KB from overall bundle size. 
$ GH_LINK https://github.com/Expensify/App/issues/31183
No new test cases required. Str.replaceAll method now makes use of built-in String.replace method. So all existing test cases should pass.
- Verified that all existing testcases pass
- Verified all functionalities are working as expected by linking into New-Expensify
Same as …
> fix: remove String.replaceAll polyfill

- lib/CONST.d.ts
- lib/CONST.jsx
Coming from https://github.com/Expensify/Web-Expensify/pull/40569
related to https://github.com/Expensify/Expensify/issues/360901
In https://github.com/Expensify/Web-Expensify/pull/40569
No QA
> [No QA] Add notifications@expensify.com to invalid emails

- __tests__/Str-test.js
- lib/str.d.ts
- lib/str.js
$ https://github.com/Expensify/App/pull/30829/files/2c877a1a00930148b6b2c468d8beb3661fb0dcff#r1465658915
> Add video utils

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
This PR is a follow up for [live markdown preview web PR](https://github.com/Expensify/App/issues/27977) as there was discovered a bug which prevent parsing when special character was inside codeFence fe. ` ``` one > two ``` `.
To fix this issue we shouldn't escape data inside codeFence `data-code-raw` attribute so the input and output of the parser will be the same for the `react-native-live-markdown` library
$ https://github.com/Expensify/App/issues/27977
There are already lots of unit tests present for covering this behaviour. All relevant ones were adjusted to new behaviour
I've checked it on example app of …
> Stop escaping codeFence data-code-raw attribute data

- lib/CONST.d.ts
- lib/ExpensiMark.js
This PR will introduce support for phone mention without `expensify.sms` suffix.
@c3024 @jasperhuangg 
One question I have is now I have not made `+` sign to be mandatory in the beginning of the mention but we can make it mandatory. Need your thoughts on this.
$ https://github.com/Expensify/App/issues/33902
> Added support for phone mention without `expensify.sms` suffix 

- __tests__/URL-test.js
- lib/Url.js
This PR improves the performance of URL parsing regular expression by preventing matching of urls nested inside html tags like `<code>`, `<pre>` etc. This was causing performance issues on mobile devices. The PR adds an early return in regex matching by excluding links inside tags and there by avoiding the need to validate the string for possible TLDs which is more than 10K characters long.
$ GH_LINK https://github.com/Expensify/App/issues/34324
Details: https://github.com/Expensify/App/issues/34324#issuecomment-1895303313
New test cases were added to verify that urls nested inside tags are not matched.
Tested with Expensify App to make …
> fix: prevent matching of urls nested inside tags

- __tests__/ExpensiMark-HTML-test.js
- lib/CONST.d.ts
- lib/CONST.jsx
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/34307
2. Send a message with emoji
3. See the `html` of the message and verify that the emoji is wrapped in a `emoji` tag
2. Send a message with emoji
3. See the `html` of the message and verify that the emoji is wrapped in a `emoji` tag
Same as above
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
<summary>MacOS: Desktop</summary>
</details>
> Add emoji rule

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
This PR adds support for nested quotes. Maximal level of quotes is set to *3*. 
Additionally it fixes bug with double removal of `>` symbol
$ https://github.com/Expensify/App/issues/36227
Every test involving writing messages with quotes will be relevant in this case, as the behaviour of single quotes shouldn't be changed. In addition, every such a test can be tweaked to check nested quotes case simply by adding additional `>` symbol
I've checked it by running all unit tests and by linking it in E/App and checking in chat itself
I'm going to add additional unit tests which should be sufficient to cover all popular cases. Morove manual …
> Add support for nested quotes

- __tests__/URL-test.js
- lib/Url.js
This reverts commit 83ae6194b3e4feb363ea9d061085a7ab76e35ffb where we modified the `URL_WEBSITE_REGEX` to prevent excessive backtracking. This however caused regression https://github.com/Expensify/App/issues/37472. So reverting the commit to unblock other PRs. Will raise a new PR with fix.
$ https://github.com/Expensify/App/issues/37472
> Revert #651

- lib/Log.jsx
- lib/Network.jsx
If API uses a new format `/api/command?` then this will properly strip out the command and add it to the URL. 
Off hold since we patched Salt/our nginx config on secure, web prod and staging.
For https://github.com/Expensify/Web-Expensify/pull/41231
1. With the other PRs listed in the original, test Web-E, App, Web-Secure, etc. and see that `/api/{command}` properly handles all commands and returns the expected values, while logs show little to no difference in the actual request received. 
N/A
> Support new API formats in Network.jsx

- lib/ExpensiMark.js
This PR fix blockquote limiting bug that appears when pasting more than 3 `>` and text after them. ExpensiMark on first parsing returns 4 blockquotes instead of 3 (limit is 3)
https://github.com/Expensify/expensify-common/assets/39538890/78e6dc5c-c90b-4e5c-8f62-5577e2396ead
$ https://github.com/Expensify/App/issues/36227
1. Open New Dot App on native devices
2. Write inside the Composer `>>>> Test`
3. Input should show only 3 blockquotes
4. Send the message
5. Verify if sent message has only 3 blockquotes
Verify if with this changes bug is fixed on all native platforms or on the [web live markdown PR](https://github.com/Expensify/App/pull/38152)
> Fix blockquotes limiting in ExpensiMark

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/37533
The ExpensiMark-HTML-test.js is updated to include the new changes case.
Ran the unit test.
Testing in App (Android & iOS only):
- Type these markdowns into composer:
```
~```a```~
*```b```*
_```c```_
[```d```](google.com)
```
- Verify the strikethrough, bold, italic, and auto link isn't applied
_to be able to test these changes, you need to apply the code change to react-native-live-markdown-parser.js_
_find all occurrences of `includes('<pre>')` and replace it with `includes('</pre>')`_
https://github.com/Expensify/expensify-common/assets/50919443/52715995-693c-4f38-a9f4-871c4e966dea
1. …
> Prevent bold, italic, strikethrough, and auto link when the content is a codefence

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-HTMLToText-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
This Pull Request introduces enhancements to the ExpensiMark library by implementing the conversion of image markdown syntax to HTML `<img>` tags and vice versa. It covers various cases including handling single images and text containing images. 
Additionally, it addresses the conversion of `<img>` tags back to markdown. 
An issue with image alt text containing markdown not converting to plain text is acknowledged and currently marked as a limitation.
$ https://github.com/Expensify/App/issues/37246
1. **Unit/Integration Tests Covering the Change:**
- The changes are covered by unit tests added to `ExpensiMark-HTML-test.js`, `ExpensiMark-HTMLToText-test.js`, and `ExpensiMark-Markdown-test.js`. These tests validate the conversion of image markdown to HTML tags, the handling of images with …
> Add support for inline image Markdown

- __tests__/URL-test.js
- lib/Url.js
This PR improves the performance of URL parsing regular expression by preventing  catastrophic backtracking . This was causing performance issues on mobile devices. The PR adds an early return in regex matching by excluding text that doesn't match a url pattern and there by avoiding the need to validate the string for possible TLDs which is more than 10K characters long.
This is a reattempt to fix the issue, which had caused a regression earlier. https://github.com/Expensify/expensify-common/pull/657
$ https://github.com/Expensify/App/issues/34324
Proposal: https://github.com/Expensify/App/issues/34324#issuecomment-1895303313
New test cases were added to verify that urls nested inside tags are not …
> fix: optimise url matching regex

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
This PR is an optional followup for https://github.com/Expensify/expensify-common/pull/658 if we'd like to patch a problem where image attribute content is being parsed to HTML as detailed in: https://github.com/Expensify/expensify-common/pull/658#discussion_r1508088239
$ https://github.com/Expensify/App/issues/37246
1. **Unit/Integration Tests Covering the Change:**
- The changes are covered by unit tests added to `ExpensiMark-HTML-test.js` and `ExpensiMark-Markdown-test.js`. These tests validate that MD content designated for the `alt` attribute is escaped as HTML entities so it isn't converted to html tags by following rules
2. **Tests Performed to Validate Changes:**
- Ran all newly added tests and ensured they pass, verifying the correct conversion of markdown to HTML `<img>` tags …
> Add support for inline image Markdown - attribute fix

- __tests__/Str-test.js
- lib/CONST.d.ts
- lib/CONST.jsx
- lib/ExpensiMark.js
- lib/str.d.ts
- lib/str.js
Current `isValidPhone` function only validates E.164 standard phone numbers but not others causing misunderstandings and worng usages. This PR:
1. Mark `isValidPhone` as deprecated
2. Replace `isValidPhone` with `isValidE164Phone`
3. Add a new `isValidPhoneFormat` to validate phone numbers in different formats
```
significant: 4404589784
international: +1 440-458-9784
e164: +14404589784
national: (440) 458-9784
123.456.7890
```
$ https://github.com/Expensify/App/issues/37723
**1. What unit/integration tests cover your change? What autoQA tests cover your change?**
This is a renaming refactor so no need to add new unit tests.
**2. What tests did you perform that validates your changed worked?**
- Test in Expensify App follow these steps:
1. Go to Workspace > Bank account.
4. Initiate the …
> Validate phone numbers in different formats

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
This PR enables indented text to show as is (do not trim the spaces) in quotes.
$ https://github.com/Expensify/App/issues/38156
**1. What unit/integration tests cover your change? What autoQA tests cover your change?**
The `ExpensiMark-HTML-test.js` is updated to include the new test cases and modify existing tests to match with new expected behaviors.
**2. What tests did you perform that validates your changed worked?**
- Run the unit test.
- Test in Expensify App follow these steps:
1. Send a quote message with indentation:
```
> No indent
>     Indented 4
```
2. Verify the `Indented 4` line shows with 4-space indentation in quote
**1. What does QA need to do to validate your changes?**
Test in Expensify App follow these steps:
1. Send a quote message with indentation:
```
> No indent
> …
```
> Allow indented text in quotes

- __tests__/Str-test.js
- lib/CONST.jsx
Corrected the phone number regex by adding the startswith(^) and endswith($) characters. Follow-up of PR https://github.com/Expensify/expensify-common/pull/672
cc: @grgia 
$ https://github.com/Expensify/App/issues/37723
https://github.com/Expensify/App/issues/37723#issuecomment-2036724546
1. Unit tests have been updated in tests/Str-test.js to cover invalid number scenario.
https://github.com/Expensify/expensify-common/assets/14358475/d2970351-7f52-45e3-8d29-f996de12f9b2
> Fixed phone number regex

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
> [!IMPORTANT]
> Room mentions consists of `#` symbol followed by room name. Room name consist of any char sequence connected by hyphens (no spaces is allowed inside room name)
$ https://github.com/Expensify/App/issues/39538
I've created multiple unit tests to cover most of the possible usages of room/report mentions. Room mentions consists of `#` symbol followed by room name 
Check if existing unit tests are not failing after my. changes, added additional tests to cover room mentions
Room mentions are not yet visible inside E/App, so to validate this changes we should only check for …
> [Mentions v2] Add new rule in ExpensiMark for room mentions

- lib/ExpensiMark.js
$ Issue: https://github.com/Expensify/App/issues/38522
$ Proposal: https://github.com/Expensify/App/issues/38522#issuecomment-2009006697
1. Open any report
2. Compose a multiline message with bold and codeblock:
``` 
bold
```*not a bold*```
This is *bold* 
```
3. Should render
bold
```*not a bold*```
This is **bold**
<details>
https://github.com/Expensify/expensify-common/assets/113963320/b4cf5890-8de7-432f-abbf-d10a478cb3ad
</details>
<details>
https://github.com/Expensify/expensify-common/assets/113963320/ceb2595d-5dc9-442a-8fc8-5068823f7955
</details>
<details> …
> fix bold markdown display incorrectly

- __tests__/ExpensiMark-HTMLToText-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/38877
1. Go to staging.new.expensify.com
2. Go to any chat
3. Send a message with inline image markdown. Example:
```
An inline image and some text ![off](https://images.unsplash.com/photo-1709983723739-d72ea88434dd?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D)
```
4. Go to a different chat
5. Go back to the chat in Step 3
6. Verify that LHN preview will show "text [Attachment]" format after returning to the same chat
> fix LHN preview shows incorrect message with attachment

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
This PR introduces refinements in the `ExpensiMark` library to enhance the handling of markdown syntax for images, including the introduction of shorthand syntax for images without alt text, and refines the cleanup of HTML attributes
$ https://github.com/Expensify/App/issues/38952
1. Unit tests have been updated in `__tests__/ExpensiMark-HTML-test.js` and `__tests__/ExpensiMark-Markdown-test.js` to cover the new markdown shorthand for images without alt text, the handling of images with empty and special characters in alt text, and the refinement in HTML attribute cleanup. These tests validate the parsing of markdown to HTML and vice versa, ensuring that the changes behave as expected.
1. Manual tests were conducted to verify that the new markdown shorthand for images is correctly …
> 🔧 ExpensiMark: Markdown image shorthand syntax

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-HTMLToText-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.d.ts
- lib/ExpensiMark.js
This PR consists of two different changes
1.  `htmlToMarkdown` method now has additional, optional argument `extras` this argument adds the possibility to pass extra data which can be used in replacement function. For now is used to pass accountID to name and reportID to name maps
2. `replace` method has additional object key `disabledRules`. Every rule name from this array will be skipped in parsing.
$ https://github.com/Expensify/App/issues/40480
https://github.com/Expensify/App/issues/39550
The changes, which this PR introduces, allows to more precisely interact with parser. To be precise, now we will be able to pass application state to the parser itself. We wrote couple of unit tests which mocks …
> Pass extra data (fe. accountIDs) to HTMLToMarkdown method & add possibility to disable certain rules

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
Extends the implementation of `userMentions` to include explicit `rawInputReplacement` function.  With this change we ensure that input string is not changed when `shouldKeepRawInput` flag is raised
$ https://github.com/Expensify/App/issues/40414
I"ve added unit test to catch the situation when input string contains phone number mention and `shouldKeepRawInput` flag is raised.
I've tested it inside `react-native-live-markdown` example library - with this change we no longer experience console.error described in linked issue.
Updating `expensify-common` version inside parser directory of …
> Create explicit `rawInputReplacement` function for userMentions

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
This PR changes quote regex to enforce following space after `>`.
`>` not followed by space won't be parsed as quote. In the multiple level quote context spaces between `>` signs are irrelevent
$ https://github.com/Expensify/App/issues/41696
I've Adjusted already present unit tests 
I've run unit tests and checked the changes in both example app of `react-native-live-markdown` and E/App itself, by bumping the expensify-common version to my branch head
bump expensify-common version in E/App and use chat normally - sent messages should be parsed with the new rule
1. What areas to they …
> Recognise only blockquotes followed by space

- __tests__/ExpensiMark-HTMLToText-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.js
- package-lock.json
- package.json
$ [42161](https://github.com/Expensify/App/issues/42161)
> Add missing default value to `extras`

- lib/CONST.jsx
It's already in the corresponding const `INVALID_APPROVER_AND_SHAREE_EMAILS` in `CONST.d.ts`. It was accidentally omitted in https://github.com/Expensify/expensify-common/commit/25d49ac1271152ff8f42dd862f53987aa70d91de
Part of https://github.com/Expensify/Expensify/issues/392651
N/A
None
> Add `notifications@` as an invalid account to share reports with

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
We're currently working on adding styles to `code fence` & `inline code` blocks to Live Markdown. After some [discussion](https://swmansion.slack.com/archives/C06BDSWLDPB/p1713274778358479) regarding `code fence`/`pre` block we agreed that the best way to handle it is to limit the accepted syntax variations.
This PR adds these changes directly to ExpensiMark 🙌🏻 
$ [GH_LINK](https://github.com/Expensify/App/issues/39518)
All of the tests that have changed in this PR
I tested it both in Live Markdown & in the Expensify App to make sure that it didn't break anything
Check if there's just …
> Change accepted syntax for code fence

- __tests__/ExpensiMark-HTMLToText-test.js
- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.d.ts
- lib/ExpensiMark.js
This PR changes field name of extras in ExpensiMark to fix type check fails.
Modify mention user and mention report extras field names in ExpensiMark htmlToText and htmlToMarkdown rules
$ https://github.com/Expensify/App/issues/40928
typecheck on expensify/App should run successfully
I have tested it on my other PR, thread report from report action that contains mention room and mention user should display report name properly in header report and in LHN.
N/A
N/A
> Modify mention user and mention report extras field names in ExpensiMark htmlToText and htmlToMarkdown rules

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/41110
This PR is to fix italicizing the context which are following `<code>,<pre>,<a>` tags in one line.
Passed all existing test cases and Added one more test case for this purpose.
bump expensify-common version in E/App and `react-native-live-markdown` to this PR and tested locally
bump expensify-common version in E/App and use chat normally - sent messages should be parsed with the new rule
1. What areas do they need to test for regressions?
Italic markdown following `<code>,<pre>,<a>,<mention-user>` tags in one line
> Improve markdown italicizing when following tags

- lib/ExpensiMark.d.ts
- lib/ExpensiMark.js
Currently using `Log.alert` in `ExpensiMark` [causes E/App to crash](https://github.com/Expensify/App/issues/42161#issuecomment-2145151574), to avoid this we want to add possibility to set your own logger in `ExpensiMark` and provide errorless default logger that just `console.warns`. 
$ https://github.com/Expensify/App/issues/42161
> Add static logger to ExpensiMark

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
This PR changes the way we parse blockquotes in shouldKeepRawInput mode - empty blockquotes will not be excluded by the regex.
$ https://github.com/Expensify/App/issues/41107
There are no tests verifying the shouldKeepRawInput flag paths, but all the existing tests are passing as expected (the logic is supposed to change only for the react-native-live-markdown).
I verified how it works by applying a proper patch including a modified regex in react-native-live-markdown.
bump expensify-common version in E/App and use chat normally - sent messages should be parsed with the new rule
2. What …
> Allow empty blockquotes

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.js
Update `rawInputReplacement` of `userMetion` rule to not display as `mention` for the invalid phone number in the live preview.
$ https://github.com/Expensify/App/issues/41078
The auto test is updated and added.
> fix mention preview with invalid phone number

- package-lock.json
The main dependency `jest-environment-jsdom` does not have any updates so I updated the package with `npm update ws`
$ https://github.com/Expensify/Expensify/issues/407146
It's a dev dependency for tests so as long as tests are still passing, we should be good.
N/A
> Update packages to fix vulnerabilities

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.ts
CC @marcaaron @lakchote @eh2077 
When We copy `<mention-user accountID="1234" />` as `text/html` to clipboard on the web [here](https://github.com/Expensify/App/blob/571a79d3d43f68ace68406a2e4bcb17604289103/src/libs/Clipboard/index.ts#L119-L123). The paste value [here](https://github.com/Expensify/App/blob/d0513b9513a091cb49f79fbc429b73d2a987cfce/src/hooks/useHtmlPaste/index.ts#L109) paste with different format `<meta charset='utf-8'><html><head></head><body><mention-user accountid="1234"></mention-user></body></html>`
(`<openTag></closeTag>` not `<closedTag />`), and this format not match rule `reportMention` in `ExpensiMark`
This issue will update htmlToMarkdownRules `userMention` and `reportMention` regex to work for both self closing and non self closing tags.
$ …
> update htmlToMarkdownRules userMention and reportMention

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.ts
Use new logic to check bold text: https://github.com/Expensify/App/issues/41109#issuecomment-2095057640
$ https://github.com/Expensify/App/issues/41109
Tests and QA steps:
1. Type anything on a Google document.
2. Copy it.
3. Paste it in Expensify.
4. Check if the font is still normal (it shouldn't be bold).
5. Now, type something in bold text on a Google document.
6. Copy/paste to Expensify.
7. It should show in bold.
https://github.com/Expensify/expensify-common/assets/35566748/86e457a4-919a-46af-b261-8d9565763be8
https://github.com/Expensify/expensify-common/assets/35566748/3c22cbc6-c51e-42b3-b318-f918907035aa
> Use new logic to check bold text

- __tests__/ExpensiMark-HTML-test.js
- lib/CONST.ts
- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/44835
Updated unit test.
a. Send a link with emoji as text (`[😄 link](google.com)`) to any user
b. Verify `😄 link` is rendered as a link
Web
Desktop
iOS mWeb
iOS
Android mWeb
Android
Same as Test step above
> Allow emoji as link text

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.ts
Fix if underscore ahead of `*` not result in a bold style
https://github.com/Expensify/App/issues/44032
1. What unit/integration tests cover your change? 
A unit test is added in this PR.
Apply this change to expensify/App to test.
typing _*any words* should result in a bold 
NA
I have read the CLA Document and I hereby sign the CLA
> Fix underscore ahead of asterisk not get bolded

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/43386
This PR is to fix parsing markdown for multiline email hyperlinks
Passed all existing test cases and Added one more test case for this purpose.
bump expensify-common version in E/App and `react-native-live-markdown` to this PR and tested locally
bump expensify-common version in E/App and try to input multiline email hyperlinks ( i.e. [test\ntest](test@test.com) ) and see if there's any errors or wrong parsing.
> fix parsing markdown for multiline email hyperlink

- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.ts
- lib/components/form/element/combobox.js
- lib/str.ts
- lib/utils.ts
This PR renames `escape` and `unescape` functions in `Utils` module to `escapeText` and `unescapeText`, accordingly.
The reason for this change is that, although deprecated, both `escape` and `unescape` are built-in JavaScript functions:
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape
Hence, these names might be confusing for other third-party libraries that rely on this rule, e.g. Reanimated Babel plugin.
These changes are needed for `ExpensiMark` to work properly in worklets in `react-native-live-markdown`:
* https://github.com/Expensify/react-native-live-markdown/issues/317
$ GH_LINK
1. What unit/integration tests cover your change? What autoQA tests …
> Rename `escape`/`unescape` to `escapeText`/`unescapeText`

- lib/ExpensiMark.ts
- lib/str.ts
- lib/utils.ts
This PR adds `'worklet';` directive in file `ExpensiMark.ts` (as well as some of its dependencies, namely `str.ts` and `utils.ts`) so that class `ExpensiMark` can be used instantiated and used in [worklets](https://docs.swmansion.com/react-native-reanimated/docs/guides/worklets/).
When `'worklet';` directive is located at the top of the file, all functions, classes and object methods in the top-level scope of within this file are workletized.
Worklets are short-running JS functions that can be run on the UI thread. We need to run ExpensiMark on the UI thread synchronously as the user types inside `MarkdownTextInput` so we can format its contents synchronously.
$ https://github.com/Expensify/react-native-live-markdown/issues/317
1. What unit/integration tests cover your change? What autoQA …
> Make it possible to use ExpensiMark in worklets

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/45635
$ PROPOSAL: https://github.com/Expensify/App/issues/45635#issuecomment-2235052840
1. Send this message:
```
~👿~ _abc_
```
2. Edit the message
3. Verify the message in edit composer matches the original message in step 1
4. Open workspace room
5. Change room description to the message in step 1 and save
6. Open room description page again
7. Verify the room description matches the original description in step 1
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
<summary>MacOS: Desktop</summary> …
> Fix `<emoji>` is mistaken as `<em>`

- __tests__/Logger-test.js
- lib/Logger.ts
$ https://github.com/Expensify/App/issues/45275
- Adjusted `Logger-test.js` to test for `extraData` argument
- Applied the changes locally to this [PR](https://github.com/Expensify/App/pull/45769). The `extraData` parameter will not be printed in the Debug Console and it's only exported to the logs file.
Following are the steps from the linked PR, which can be followed by the QA for testing.
> Testing:
> 
> - Run the app on environment other than Dev
> - Enable Client side logging
> - Close the App and re launch it
> - Click on View …
> feat: add extraData parameter to info function

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/46114
> Fix markdown in alt of video markdown

- lib/utils.ts
This PR changes `&#32` to `&#32;` in `htmlUnescapes` map in `utils.ts`.
Without this change, `unescapeText('\nHello&#32;world\n')` returns `Hello'world` (with an apostrophe) instead of `Hello world` (with space).
This breaks Markdown parsing in react-native-live-markdown (see failing tests here: https://github.com/Expensify/react-native-live-markdown/actions/runs/10217116965/job/28270172280?pr=439)
cc @roryabraham 
$ GH_LINK
> Add missing semicolon in `htmlUnescapes`

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/45623
Already in the PR
Will covered in `react-native-live-markdown` PR
Will covered in the app PR
Live markdown.
https://github.com/Expensify/react-native-live-markdown/pull/449 (Evidence is here)
> fix: no trimming for link name

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/46491
A unit test is updated
- Send a text + attachment message
- Edit the message
- Add a link (e.g., google.com) above the image markdown
- Verify the link text is rendered as a link
- Save the edit
- Verify the link message is saved as a link
To be able to test the live markdown, update the regex in `node_modules/@expensify/react-native-live-markdown/lib/parser/react-native-live-markdown-parser.js`
<details>
https://github.com/user-attachments/assets/315b0362-bc70-4b1c-9cdc-a8be8c33bad9
</details>
<details> …
> Fix autolink isn't recognized when put before img markdown

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/46891
Updated unit test to cover bold tag with style.
- Open a chat app that supports Markdown (Example: Slack)
- Send a message containing a bold markdown
- Copy the text with markdown and open NewDot
- Open any chat and paste the copied text into the compose box
- Verify the bold markdown is pasted instead of a plain text (only on Web/Desktop/iOS mWeb)
<details>
https://github.com/user-attachments/assets/f08d5df4-d814-4ba5-9a99-79dfb11ded0d
</details>
<details>
https://github.com/user-attachments/assets/37a7d42a-92bc-46a2- …
> Fix bold tag isn't rendered as markdown when it has a style

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/46917
I have add unit tests for this issue.
Update the related regex in the expensify-common in node module and send the test messages from composer of the App.
Verify the displayed message is displayed correctly.
Same as test above
Inline code and code fence related tests.
> Fix inline code regex mismatch when there is an escaped backtick character inside the backtick

- __tests__/ExpensiMark-HTMLToText-test.js
- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/47484
Test: 
1. Make the same update on `userMention` rule as in the current pr in node-modules
2. Now Open Expensify App
3. Tap on a report
4. Enter any phone mention
5. Send the message
6. Long press the message and copy to clipboard
7. Tap plus icon -- assign task
8. Paste it in title field
9. Verify sms domain doesn't exist in the text pasted
1. What does QA need to do to validate your changes? 
same as above
same as above
> Fix - Remove sms domain in htmlToText

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/45088
I have add unit tests for this issue.
Update the related regex in the expensify-common in node module and send the test messages from composer of the App.
Test example:
````
```   
test
```
````
````
```  abc 
test
```
````
The code fence/ code block must be displayed properly.
Verify the displayed message is displayed correctly.
Same as test above
Code fence related regression tests.
> Allow codefence regex to accept any characters after first three backticks

- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/48168
3. Open Expensify App
4. Tap fab - start chat -- room
5. Create 2 room with name more than 80 characters long (max 99)
6. Mention any room with name more than 80 characters
7. Verify that the room mention is shown in whisper
2. What areas to they need to test for regressions?
3. Same as above
> fix report mentions characters limit

- __tests__/Str-test.js
- lib/str.ts
$ https://github.com/Expensify/App/issues/46117
-- Added tests in `Str-test.js`
-- Applied changes to Expensify app and did normal usage of the App, since we don't have reproduction steps.
-- Probably just normal usage of Expensify App
N/A
> fix: undefined is not a function

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/48101
I have add unit tests for this issue.
Update the related regex in the expensify-common in node module and send the test messages from composer of the App.
Test example:
```
` `
```
Must be displayed as:
` `
<br />
Another test : ``` `   ` ``` must be displayed as : `   `
Same as test above
Inline code and code fence related tests.
> Add support for inline code with space only character as content

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/49276
Updated the unit test to cover an inline code block followed by an emoji within a triple backtick code block.
Update the related regex in the node_modules/expensify-common/dist/ExpensiMark.js and send this in the Expensify composer.
\`\`\`
\`diamond\` 💍
\`\`\`
Verify that the single backtick code block is not rendered within the triple backtick code block.
```
`diamond` 💍
```
Same as test above
Tests related to inline code inside code fences.
> Fix single backtick code block is rendered within a triple backtick code block when followed by an emoji

- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-Markdown-test.js
- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.ts
This PR adds caching for additional attributes to the `<img>` tags when converted to and back from Markdown.
Due to naming weirdness (current cache fields are named `videoAttributeCache` and `cacheVideoAttributes`), new fields were created on the `Extras` object: 
- `mediaAttributeCachingFn` replacing `cacheVideoAttributes`
- `mediaAttributeCache` replacing `videoAttributeCache`
Replaced fields are marked as deprecated in JS doc and will be removed after this PR is deployed and NewDot is modified so it doesn't use the deprecated fields anymore.
Logic-wise, only the deprecated properties and the new ones won't ever be used simultanously, hence caching function selection is done by detecting the presence of either deprecated or new fields. …
> Added img attribute caching to ExpensiMark

- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/46299
PROPOSAL: https://github.com/Expensify/App/issues/46299#issuecomment-2311775536 
3. Go to Expensify App
5. Tap on a room chat
6. Mention 2 user with minus sign in between i.e `#user1-#user2`
7. Verify that whisper display 2 user
2. What areas to they need to test for regressions?
8. Same as Tests
1. Go to Expensify App
2. Tap on a room chat
3. Mention 2 user with minus sign in between i.e `#user1-#user2`
4. Verify that whisper display 2 user
Same as Tests
Same as Tests
<details>
</details>
<details> …
> fix: room chat - whisper displays 1 mention when 2 mentions are send in specific way

- lib/CONST.ts
Added a list of Canadian provinces. It will be used in global reimbursements flow. This is needed in the linked issue
$ [GH_LINK](https://github.com/Expensify/App/issues/50899)
1. What unit/integration tests cover your change? What autoQA tests cover your change? N/A
1. What tests did you perform that validates your changed worked? N/A
1. What does QA need to do to validate your changes? N/A
1. What areas to they need to test for regressions? N/A
> feat: Add Canadian provinces to CONST

- lib/API.jsx
Just a missing command so the already deployed code for resetting SMS delivery failure status in Web-E can work as expected :)
https://github.com/Expensify/Expensify/issues/335408
Same as https://github.com/Expensify/Web-Expensify/pull/44736
QA
Same as https://github.com/Expensify/Web-Expensify/pull/44736
> Add resetSMSDeliveryFailureStatus command

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.ts
This PR fixes the issue that the inline code block regex doesn't match two backticks with no content between them.
For example, in 
`hello` `` hi`
the two backticks in the middle are not regarded as a pair, which causes the word _hi_ after them to be part of the code block. However, the user expects the word _hi_ not to be part of the code block.
$ https://github.com/Expensify/App/issues/53573
A similar issue is also mentioned in [this comment](https://github.com/Expensify/App/pull/52780#issuecomment-2535937359).
Test string: "`hello` `` hi`"
Expected result: "<code>hello</code> &#x60;&#x60; hi&#x60;"
Expected result before: "My favorite language is <code>&#x60;JavaScript&#x60;</code>. How about you?" …
> Fix double backticks

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.ts
This PR removes replacing whitespaces with &nbsp; in raw input mode, so the Live Markdown Input can render markdown styles when there are only spaces between backticks ` `
https://github.com/Expensify/App/issues/53457
1. Set the `shouldKeepRawInput` prop to `true`
2. Verify if the output for `' '` (replace ' with `) is the same and the input
1. What areas do they need to test for regressions?
> Remove &nbsp; from inline code block in raw input mode

- __tests__/ExpensiMark-HTMLToText-test.js
- lib/ExpensiMark.ts
This PR fixes the issue that the mention report and mention user sometimes has no quotation marks
Update `htmlToTextRules` userMention and reportMention regex to work for both `<selfClosedTag />` and non self closing tags `<openTag></closeTag>` to be like htmlToMarkdownRules
Example:
$ https://github.com/Expensify/App/issues/54630
```
// mention-user
Test string: "<mention-user accountID=1234></mention-user>"
Expected result: "@user@domain.com"
Test string: "<mention-user accountID=1234 />"
Expected result: "@user@domain.com"
// mention-report
Test string: "<mention-report reportID=1234/>"
Expected result: "#room-name"
```
- Create a …
> fix: mentions are not shown in invite user or remove user report

- .eslintrc.js
- __tests__/ExpensiMark-HTML-test.js
- __tests__/ExpensiMark-test.js
- lib/CONST.ts
- lib/ExpensiMark.ts
This is part of allowing to style and highlight short-mentions inside live-markdown when user is writing/editing their message. More details here: https://github.com/Expensify/App/issues/38025#issuecomment-2566338328
The purpose of this PR is to add handling of (_possible_) short mention tags to ExpensiMark.
In this PR we define "short-mention" as anything after `@` character that would be a valid email prefix.
Examples:
- valid short mentions: @mateusz.titz, @test.com, @john.doe, @jane123456
- **invalid** short mentions: @mateusz.titz@swmansion.com (<-- standard mention), @+12345
The only way for us to actually render short-mentions inside `react-native-live-markdown` (and other code using ExpensiMark) is to somehow have the list of all possible user logins, and then checking whether the …
> Add handling short mentions tags to ExpensiMark

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/58215
$ PROPOSAL: https://github.com/Expensify/App/issues/58215#issuecomment-2714963469
1. Paste this message into the composer in App:
```
~_**Zoom**_~
*Test*
```
2. Verify `*Zoom*` is formatted with bold, italic and strikethrough
3. Verify `Test` is formatted with bold
4. Send the message
5. Verify `*Zoom*` and `Test` are formatted with bold
1. Paste this message into the composer in App:
```
~_**Zoom**_~
*Test*
```
2. Verify `*Zoom*` is formatted with bold, italic and strikethrough
3. Verify `Test` is formatted with bold
4. Send the message
5. Verify `*Zoom*` and `Test` are formatted with bold
> fix: multiple bolds with </em> in between are not rendered correctly

- lib/ReportHistoryStore.jsx
When fetching all of the report's action to refresh them, we don't need to do any merging but simply update the cache.
$ https://github.com/Expensify/Expensify/issues/489667
I used [localJS](https://stackoverflowteams.com/c/expensify/questions/29) and supportalled into events@culturalcare.com / report  https://www.expensify.com/report?param=%7B%22pageReportID%22:%22877821327596826%22,%22keepCollection%22:true%7D  and made sure the report action `FORWARDED` is showing  in report page.
Before:
After:
1. Supportal into events@culturalcare.com, go to report https://www.expensify.com/report?param=%7B%22pageReportID%22:%22877821327596826%22,%22keepCollection%22:true%7D and verify actions show up as in the "After" screenshot above.
> Add new method to merge report actions by reportActionID

- lib/Templates.jsx
- package-lock.json
- package.json
We're bringing back underscore to be used in the templates file only because there's way too many changes needed in Web-E to make it work, we'll be doing that separately. For now we need to fix a customer issue ASAP.
$ https://github.com/Expensify/Expensify/issues/489667
1. Make sure various pages load fine in Web-E.
N/A will be tested in Web-E
> Bring back underscore to fix broken templates from Web-E

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.ts
This PR fixes an issue where the regex for room mentions (`#room-name`) was not matching case when the `#` symbol was preceded by `:` character
https://github.com/Expensify/App/issues/57195
- Verify the `#test-room` string matches the room name if the string is:
`:#test-room`
Test steps:
```
1. Create a room named `test-room-name`
2. Open the admin room of the workspace in step 1
3. Send `:#test-room-name` message
4. Verify the `#test-room-name` is highlighted
```
https://github.com/user-attachments/assets/d6392dac-fbad-427b-a244-54698115e7d2
2. What areas to they need to test for …
> fix: update mention room regex

- __tests__/ExpensiMark-Markdown-test.js
- lib/ExpensiMark.ts
Supporting change for fixing https://github.com/Expensify/App/issues/57241.
* Added "Test long HTML header" to `__tests__/ExpensiMark-Markdown-test.js`
* Tested on all platforms from App code modified to use new `maxBodyLength` parameter.
* Tests include HTML clipboard paste on platforms where available.
* Tests included very large clipboard pastes to check for performance issues. There was some lag but it was similar both before and after this change.
* Inspected all calls to `htmlToMarkdown()` from Expensify repo and none will be affected by the additional parameter.
* Run unit tests. …
> feat: add maxBodyLength parameter to htmlToMarkdown

- lib/Logger.ts
Was looking into logs from devices [here](https://expensify.slack.com/archives/C05CBC62HGW/p1748258520108139?thread_ts=1748256347.169089&cid=C05CBC62HGW) and realized that 50 is way too small, so adding a config to control this.
None, will test in [App](https://github.com/Expensify/expensify-common/pull/854) once it is merged (but I could test if someone answers [this](https://expensify.slack.com/archives/C03TQ48KC/p1748259786357109))
No
> Add a config for the max log lines before flushing in logger

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.ts
Fix the regular expression that processes underscores in markdown to correctly handle two back-to-back words, for example:
```
_test__test_
```
There are two changes to the (already pretty complicated) regex that's matching the "_":
1. To fix the current issue, add a positive lookbehind to allow "_": `(?<=_)`
2. To not break the existing test case of hello__world (which should not get italicized), add a negative lookbehind to not match an underscore in the middle of a word: `(?<!\b[^\W_]*_)`
$ https://github.com/Expensify/App/issues/59790
Added test named "Test italic markdown replacement with consecutive italicized strings with no space" in `ExpensiMark-HTML-jest.js`
2. What tests did you perform that …
> handle back-to-back underscore/italic in markdown

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.ts
This PR updates the codeblock parsing rule so it:
1. Doesn't accept any text before the code block opening syntax 
2. Require a new line after the code block opening syntax and before the closing syntax
We introduce this change to make parsing rules when typing markdown text inside the Live Markdown input more similar to the result that the user can see after sending the message in E/App. The above changes allow us to create a more intuitive and logical way to use code blocks when typing. Simplifying the parsing rules will also protect us from many complex and hard styling possibilities in the future.
This PR is part of code fence and inline code block refactor in the `react-native-live-markdown` library - [PR](https://github.com/Expensify/react-native-live-markdown/pull/456) …
> Update codeblock parsing rule

- lib/utils.ts
When I was trying to use `react-native-worklets` with `react-native-live-markdown` https://github.com/tjzel/react-native-live-markdown/pull/1 I noticed that not explicitly using `globalThis` in these helper functions makes them fail - the `navigator` object is copied from the RN Runtime to the UI Runtime, instead of checking if it's available on the caller runtime. This change should have no other effect.
> chore: use globalThis when checking for window and navigator

- package-lock.json
There has been a small bump since the issue got reopened: https://github.com/Expensify/Expensify/issues/399651. I ran `npm update micromatch`, which is why only the package-lock file was updated.
$ https://github.com/Expensify/Expensify/issues/399651
This is only used in dev packages (grunt and jest)
No QA.
> [No QA] Update micromatch to fix security vulnerabilities

- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/63711
https://github.com/user-attachments/assets/07d6019f-ff64-4d4f-8c4c-6b8837fed160
> remove truncation when convert html to markdown

- lib/fastMerge.ts
We've tried updating `expensify-common` to the latest version (2.0.144) in the `react-native-live-markdown` repo, but encountered crashes due to invalid fastMerge file workletization caused by https://github.com/Expensify/expensify-common/pull/855. Because in this file we can find double-function recursion and worklets aren't hoisted, it results in a crash with an error: `Cannot access 'fastMerge' before initialization`.
In this PR, I'm breaking double function recursion and moving the `mergeObject` code inside the `fastMerge` function. It shouldn't affect anything since `mergeObject` isn't exported, only `fastMerge` was using it.
$ https://github.com/Expensify/App/issues/39518
1. Verify if E/App isn't crashing in LHN with this change
2. Verify if the `live-markdown` example app isn't …
> Fix fastMerge worklet

- __tests__/ExpensiMark-Markdown-test.js
- __tests__/ExpensiMark-test.js
- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/65244
PROPOSAL: https://github.com/Expensify/App/issues/65244#issuecomment-3041145770
Same as QA Steps
Same as QA Steps
1. Open https://staging.new.expensify.com/
2. Go to any chat
3. Type ">" and space for creating quote markdown
4. Press Shift Enter
5. Type anything on the second line and send message
6. Copy this message
7. Paste this message to composer box
8. Note that the pasted message is same as original
<details>
https://github.com/user-attachments/assets/42544b66-f1c8-4e0b-9c20-5655f2feed8a
</details>
<details>
https://github.com/user-attachments/assets/a200dc6f-9297-442c-a745-da32bc1d012a
</details>
<details> …
> Fix/65244 - Paste the copied message having quote markdown displays wrong line with original

- lib/APIDeferred.jsx
- package-lock.json
- package.json
Fixes an issue found when testing [this PR](https://github.com/Expensify/App/pull/62314), where the backend returns the response `"404 No user with that partner/userID"` when [trying to log in again](https://github.com/Expensify/Web-Expensify/blob/8bdc12e05262b41119e50cd2459a51e5069978dd/homepage/js/signin.jsx#L2443-L2456), after the user has been signed out from signout.php, via a redirect from New Expensify. If any APIDeferred returns a non-200 jsonCode and there isn't an error handler set up for it, when we try to access the error handler it will fail. Now I have fixed checking for the error handler so it works even if one doesn't exist.
1. Check out this [App PR](https://github.com/Expensify/App/pull/62314) and build the dev site
3. Run `npm link` in expensify-common
4. In Web-E run …
> [No QA] Fix checking for jsonCode error handlers

- .prettierrc.js
- lib/CONST.ts
CC @AndrewGable @madmax330 
Coming from discussion here https://expensify.slack.com/archives/C03SSAQ7P/p1754285585977329, we observed that a few constants that were removed as part of deleting `00constant.js` file exists nowhere in our codebase and resulted in a few regression so through this PR we try to backfill the missing constants.
N/A
1. Login to OldDot.
2. Navigate to `Settings > Wallet`.
3. Click on `Import Card/Bank` and select any option among first 6.
4. Confirm `Log In` page is shown.
Same as tests.
> Add more constants since web-s has a constant file deleted

- lib/fastMerge.ts
Coming from https://github.com/Expensify/App/pull/66775
With [PR #869](https://github.com/Expensify/expensify-common/pull/869), the type of `fastMerge` was changed, causing every input type to fall back to `Record<string, unknown>`. This PR restores `fastMerge`’s original typing by overloading its function signature.
$ https://github.com/Expensify/App/issues/65244 
PROPOSAL: 
No test
No test
No test
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
<summary>MacOS: Desktop</summary>
</details>
> [No QA] Fix TypeScript run failed error

- __tests__/ExpensiMark-HTML-test.js
- lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/69685
Added a new caes to the unit test
Same as QA
In Expensify App
Prerequisite: login with a private domain, create a WS, and invite a user with the same private domain
1. Open the WS chat chat
2. Send a short mention with a single character followed by dot (for example, @j.doe)
3. Verify the mention is recognized
<details>
https://github.com/user-attachments/assets/ac2ee51e-ace0-4d2a-822b-946895bae847
</details>
<details>
<summary>Android: mWeb …
> Fix short mention with single character followed by dot isn't recognized
