lib/API.jsx
cc @Gonals will you please review this? (Follow up on previous PR)
Part of review comments from this PR https://github.com/Expensify/Web-Expensify/pull/29932 to use this existing api endpoint instead of creating a new one https://github.com/Expensify/Expensify/issues/146558
Part of https://github.com/Expensify/Expensify/issues/146558
Used in testing in Web-E PR
=> Add Get API endpoint and remove ActivePolicy_GetID [No QA]

.github/CODEOWNERS.md
$ https://github.com/Expensify/Expensify/issues/149443
Will be tested internally post-merge (this is a GH feature so we've gotta merge it to test it)
=> Added CODEOWNERS.md file

__tests__/ExpensiMark-test.js, lib/ExpensiMark.js
cc @rafecolton 
Needed to fix https://github.com/Expensify/Expensify/issues/153365
1. Automated tests updated
Will be qa'd in the Expensify.cash pr
=> Add some missing special characters to the link regex

README.md
@marcaaron can you review this please?
cc @roryabraham 
$ https://github.com/Expensify/expensify-common/pull/329#issuecomment-775560984
=> Return to old hash-based deploy instructions

.github/workflows/cla.yml
Quick update for CLA bot to latest version to improve developer experience.
Fixes https://github.com/Expensify/Expensify/issues/153655
=> Update CLA bot version

.eslintrc.js, __tests__/GithubUtils-test.js, lib/GithubUtils.js, package-lock.json, package.json
@roryabraham  will you please review this?
$ https://github.com/Expensify/Expensify/issues/155326
1. Automated tests
2. If you want to see it not use mocks you can set `GITHUB_TOKEN` env variable and run this test (expect it to fail, but see real API results in failure)
```js
test('Test finding an issue', () => {
const octokit = new Octokit({
auth: process.env.GITHUB_TOKEN
});
const github = new GithubUtils(octokit);
return github.getStagingDeployCash().then(data => expect(data).toStrictEqual(expectedResponse));
});
```
1. N/A
=> Add StagingDeployCash logic

__tests__/GithubUtils-test.js, lib/GithubUtils.js
@AndrewGable will you please review this?
$ https://github.com/Expensify/Expensify/issues/155336
Automated unit tests added.
None.
=> [No QA] Create JS utility to update StagingDeployCash

__tests__/Str-test.js, lib/str.js
Added a method to `Str.js` to check for valid URLs
$ https://github.com/Expensify/Expensify/issues/156558
Automated tests. Will also be tested with the Web-Secure version bump PR
No QA
=> Add Str method to check for valid URL

lib/CONST.jsx
Add sasktel.net to public domains
Coming from https://stackoverflow.com/c/expensify/questions/4799
related to https://github.com/Expensify/Expensify/issues/157784
none
n/a
=> [No QA] Add sasktel.net to public domains

lib/CONST.jsx
Add chronos@expensify.com to the list of Expensify email accounts.
$ https://github.com/Expensify/Expensify/issues/157087
1. No
1. No
=> Add chronos to list of expensify emails

__tests__/ExpensiMark-test.js, lib/ExpensiMark.js
$ https://github.com/Expensify/Expensify/issues/153365#issuecomment-812037925
1. Automated tests
2. Applied changes to Expensify.cash locally
3. Sent the message 
```
* [[Chore Checklist] Manage monthly job postings](https://github.com/Expensify/Expensify/issues/158984)
* [[Chore Checklist] Reviewing Engineer Candidate take home challenges](https://github.com/Expensify/Expensify/issues/147456) - I think this one can just be a label - maybe the `Challenge Review` label the hiring team already uses
* https://github.com/Expensify/Expensify/issues/147522 and https://github.com/Expensify/Expensify/issues/147520 - we need a more holistic solution for these. I have some ideas, let's discuss
* [[Expensify.org] On-duty rotation](https://github.com/Expensify/Expensify/issues/148105) - this one is a …
```
=> Support brackets inside links

__tests__/ExpensiMark-test.js, lib/ExpensiMark.js
$ https://github.com/Expensify/Expensify/issues/153365#issuecomment-825784200
$ https://github.com/Expensify/Expensify/issues/153365#issuecomment-827966767
1. automated
1. will be qa'd in the associated e.cash pr
=> Fix smart quotes and emails in links

lib/API.jsx
Needed for EW Screen Sharing project.
The API command is still WIP in Web-E, this won't be used for now.
Will be tested with the rest of https://github.com/Expensify/Expensify/issues/163733.
=> Add Inbox_Start_ScreenShare API command

package-lock.json, package.json
As the title says.
$ https://github.com/Expensify/Expensify/issues/165126
Automated tests on Web-Expensify and Expensify.cash
I ran `grunt test` on `Web-Expensify` and everything worked.
Manually checked that the main flows of Web-Expensify are working.
Manually checked that the Expensify.cash works.
N/A
=> Upgrade jQuery to the 3.6.0 version

lib/API.jsx
Helps with this https://github.com/Expensify/Expensify/issues/167260.
Used in this web-e [PR](https://github.com/Expensify/Web-Expensify/pull/31218)
None, will be tested in this web-E
None
=> Get and Set Lounge Details

lib/CONST.jsx
Copying over EXPENSIFY_EMAILS that were also added in this Web-E PR https://github.com/Expensify/Web-Expensify/pull/31380
No QA
=> [No QA] Copy over constants to EXPENSIFY_EMAILS

lib/API.jsx
Helps with this Web-E PR https://github.com/Expensify/Web-Expensify/pull/31517
None, will be tested in the Web-E PR.
None.
=> Add `isFromPublicDomain` to user API

lib/CONST.jsx
Copies over changes from PHP const EXPENSIFY_EMAILS
Conjunction with https://github.com/Expensify/Web-Expensify/pull/31738
$ https://github.com/Expensify/Expensify/issues/174077
No tests
=> [No QA] Update EXPENSIFY_EMAILS const

lib/CONST.jsx
@alex-mechler will you please review this?
Same as https://github.com/Expensify/Web-Expensify/pull/31830 & https://github.com/Expensify/App/pull/5025
$ https://github.com/Expensify/Expensify/issues/173672
No
=> Add integrationtestingcreds to EXPENSIFY_EMAILS

lib/CONST.jsx
@flodnv 
This PR replicates the same we did on https://github.com/Expensify/Web-Expensify/pull/31871, but for the JS projects.
$ https://github.com/Expensify/Expensify/issues/176665
N/A
=> [No QA] Add admin@expensify.com to the INVALID_APPROVER_AND_SHAREE_EMAILS and EXPENSIFY_EMAILS lists

lib/API.jsx
https://github.com/Expensify/Expensify/issues/178449
See linked web PR
No
=> Add short lived token API command

README.md
@chiragsalian @tgolen will you please review this?
This PR updates the readme to clarify what repos should be updated after a new PR is merged. More context in https://expensify.slack.com/archives/C03TQ48KC/p1636044257067200.
Discussion in [slack](https://expensify.slack.com/archives/C03TQ48KC/p1636044257067200)
N/A
=> Update readme to clarify what repos should be updated

lib/components/form/element/onOffSwitch.jsx
Required for https://github.com/Expensify/Web-Expensify/pull/32445
part of https://github.com/Expensify/Expensify/issues/184606
No automated tests. Tested locally in https://github.com/Expensify/Web-Expensify/pull/32445.
QA is covered by https://github.com/Expensify/Web-Expensify/pull/32445 as well.
=> [No QA] Add toggle control for onOffSwitch

lib/CONST.jsx
For https://github.com/Expensify/Expensify/issues/71013
See Associated PR
=> Add a new constant for receipts URL

lib/CONST.jsx
@iwiznia as discussed 
See https://github.com/Expensify/Web-Expensify/pull/32860 for more details & tests.
=> Update URL.RECEIPTS constant

lib/CONST.jsx
Part of https://github.com/Expensify/Expensify/issues/191720
1. BUCKET_RECEIPT: https://github.com/search?q=org%3AExpensify+BUCKET_RECEIPT&type=code
2. REPORT_SHOW_ATTACHMENTS: https://github.com/search?q=org%3AExpensify+REPORT_SHOW_ATTACHMENTS&type=code
3. REPORT_SHOW_RECEIPTS: https://github.com/search?q=org%3AExpensify+REPORT_SHOW_RECEIPTS&type=code
=> Remove unused constants related to receipts

__tests__/ExpensiMark-HTML-test.js, lib/ExpensiMark.js
https://github.com/Expensify/App/issues/8089
<details>
<summary><h4>PR Reviewer Checklist</h4></summary>
</details>
Unfortunately rn can't run on android simulator is broken :( Though i tested on real device when fixed but couldn't take screenshot at that time
=> remove codeblock space

__tests__/ExpensiMark-HTML-test.js, lib/ExpensiMark.js
Updates regex and replace logic for code block, code fence and link markdown so that non-whitespace characters are required between the marks. This fixes an issue where users can send or edit a message with empty markdown that gets replaced with empty HTML tags (an invalid comment).
$ https://github.com/Expensify/App/issues/8720
1. Log in
2. Start a chat conversation
3. Send a message with empty backticks (code block with no text in-between)
4. Verify empty backticks are sent and NOT an empty code block
5. Send a message with empty code fence backticks
6. Verify 2 code blocks with a back tick in each is sent and NOT an empty code fence
7. Send a message with a markdown link with no text
8. Verify the text is sent as is and an invisible link is NOT sent
<details>
<summary><h4>PR Reviewer …
=> Do not replace empty code block, code fence, or link markdown

lib/API.jsx
Part of https://github.com/Expensify/Expensify/issues/210381
Test with https://github.com/Expensify/Web-Expensify/pull/33768
N/a, taken care of with https://github.com/Expensify/Web-Expensify/pull/33768
=> Add method to force a cached code version update

lib/CONST.jsx
Part of https://github.com/Expensify/Expensify/issues/211521
1. Verify the report page loads in e.com
=> Add smart report agent email to constants file

__tests__/ExpensiMark-HTML-test.js, lib/ExpensiMark.js
@marcochavezf @Santhosh-Sellavel will you please review this?
With this change, links will use https:// as default instead of http://
$ https://github.com/Expensify/App/issues/9089
1. Send following links::
- google.com
- www.google.com
- http://google.com
- https://google.com
2. Expect following results respectively:
- https://google.com
- https://google.com
- http://google.com
- https://google.com
3. Edit above links and try to see if it yields expected output. 
1. Send following links::
- google.com
- www.google.com
- http://google.com
- https://google.com
2. Expect following results respectively:
- https://google.com
- https://www.google.com
- http://google.com
- https://google.com
3. Edit above links and try to see if it …
=> Make https as default application protocol

lib/CONST.jsx
Adds a new const to be used in the following Web-E PR: https://github.com/Expensify/Web-Expensify/pull/33904
$ Partially resolves https://github.com/Expensify/Expensify/issues/208493
Confirmed the const works as expected in the associated PR
N/A
=> Add SUBSCRIPTION_CHANGE_REASONS const

__tests__/ExpensiMark-HTML-test.js, lib/ExpensiMark.js
<details>
<summary>Generated description</summary>
<br />
@luacmartins  @rushatgabhane  will you please review this?
Adding new rule to replace `<br />` before the `<blockquote>`.
$ https://github.com/Expensify/App/issues/9379
`__tests__/ExpensiMark-FlatText-test.js`
```
This non-quote on the first line
> No empty new line before this blockquote
Also, there's no empty space here
> And here
```
Type the above text and should be converted to text 
`This non-quote on the first line<blockquote>No empty new line before this blockquote</blockquote>Also, there's no empty space …
=> Replace br from quote

__tests__/ExpensiMark-Markdown-test.js, lib/ExpensiMark.js
@Santhosh-Sellavel @luacmartins 
When user edit the message which contains link he/she just sent in New Expensify App, the link does not have markdown syntax around it. This PR fix it by format link as markdown link when convert HTML to markdown, and test cases have been updated too. I will create a PR which updates package.json and package-lock.json with new commit id to Expensify/App after this PR is merged.
$ https://github.com/Expensify/App/issues/9662
1. Launch the app and login
2. Send a message with link such as `https://google.com`, `http://google.com`, `google.com` to any user
3. Click action menu **Edit comment** to edit the message you just sent, verify the link has markdown syntax around it
4. Click **Save changes** to save the message, verify the link does not lose hyperlink …
=> Format link as markdown link when convert HTML to markdown

__tests__/ExpensiMark-HTML-test.js, __tests__/ExpensiMark-Markdown-test.js, lib/ExpensiMark.js
@mananjadhav @MonilBhavsar will you please review this?
Proposal:
https://github.com/Expensify/App/issues/10516#issuecomment-1235420788
$ https://github.com/Expensify/App/issues/10516
2. Type an email address using markdown for a hyperlink: eg `[abc@gmail.com](abc@gmail.com)`
3. Verify that message is displayed correctly as [abc@gmail.com](abc@gmail.com)
4. For various tests inside [], please check below 8 example cases and videos I attached for each platform
2. Type an email address using markdown for a hyperlink: eg `[abc@gmail.com](abc@gmail.com)`
3. Verify that message is displayed correctly as [abc@gmail.com](abc@gmail.com)
4. For various tests inside [], please check below 8 example cases and videos I attached for each platform
```
1. Hi, …
```
=> fix email markdown

lib/CONST.jsx
- For https://github.com/Expensify/Expensify/issues/228038
None
None
=> Update PUBLIC_DOMAINS with protonmail domains

lib/CONST.jsx
For https://github.com/Expensify/Expensify/issues/239692
None
None
=> Add spacehotline.com to list of public domains

lib/CONST.jsx
As part of fire clean up we are adding 5 domains into the list of public domains.
Partially https://github.com/Expensify/Expensify/issues/241961
=> Add 5 domains as public for fire clean up

lib/CONST.jsx
Helps with https://github.com/Expensify/Expensify/issues/243526.
Will update web-e once this is live.
None, I'll test it with web-e
None, shall be tested in web-e
=> Prompts update

lib/ExpensiMark.js
https://github.com/Expensify/App/issues/13073
The email should always be `test@gmail.com` except for 4th case it should be `_test@gmail.com`
```
test@gmail.com
*test@gmail.com*
_test@gmail.com_
*_test@gmail.com*
~_test@gmail.com_~
*_test@gmail.com_*
*_*_test@gmail.com_*_*
*__test@gmail.com__*
*__*test@gmail.com*__*
_~__test@gmail.com__~_
**__test@gmail.com__**
```
1. Login to any Expensify account
2. Go to any chat
3. Send `test@gmail.com`
4. Verify that the email is sent correctly
5. Send `*test@gmail.com*`
6. Verify that the email is sent correctly in bold format
7. Send `_test@gmail.com_`
8. Verify that the email is sent correctly in italic format
9. Send `*_test@gmail.com_*`
10. Verify that the email is sent correctly in bold and italic format
<details> …
=> Edited autoEmail regex

README.md
N/A, coming from @aldo-expensify's suggestion in https://stackoverflowteams.com/c/expensify/questions/14971/14972?noredirect=1#comment2560_14972
N/A
N/A
=> Add local package path linking option to readme

lib/API.jsx, lib/CredentialsWrapper.jsx, package-lock.json, package.json
Added Create_Login method that will be used in Web-E aka oldDot repo to implement infinite session.
$ https://github.com/Expensify/Expensify/issues/249364
N/A, we will test this with the other [PR](https://github.com/Expensify/Web-Expensify/pull/35919) where the Web-E will use this method to get a new token when the current one expires.
=> [NO QA] Added Create_Login method for infinite session

__tests__/ExpensiMark-Markdown-test.js, lib/ExpensiMark.js
When replacing html with `<p>` and `<li>` tags, it misses newlines and some spaces. This PR fixes it by
- adding a newline when replacing `<p>` tag
- adding a newline and 2 leading spaces when replacing `<li>` tag
$ https://github.com/Expensify/App/issues/12155   
PROPOSAL: https://github.com/Expensify/App/issues/12155#issuecomment-1327955648
1. Login with any account and go to any chat room
2. Open/render HTML file in a browser 
```html
<!DOCTYPE html>
<html>
<body>
<h1>HTML paragraphs and unordered list copy test</h1>
<p>This is a HTML paragraph</p>
<br>
<p>An Unordered HTML List</p>
<ul>
<li><a href="https://example.com">Coffee</a> -- Coffee</li>
<li><a href="https://example.com">Tea</a> -- Tea</li>
<li><a href="https://example.com">Milk</a> -- Milk</li>
</ul>
</body>
</html>
```
3. …
=> fix newlines and spaces when replacing <p> and <li> tags

lib/API.jsx
$ https://github.com/Expensify/Expensify/issues/259110
Tested here: https://github.com/Expensify/Web-Expensify/pull/36114
To be QAed after the version of Web-E is updated
=> Create forwardTravelDocument command

lib/CONST.jsx
$ https://github.com/Expensify/Expensify/issues/242487
N/A
N/A
=> Add allowed currencies for direct reimbursement with Corpay

lib/CONST.jsx
$ https://github.com/Expensify/Expensify/issues/259131
1. Sign into any account
2. Go to Settings > Policies > Group
3. Make a new Collect Policy
4. Toggle Auto renew Off
5. Verify that the modal looks like this:
=> Remove Subscription Change Options

lib/CONST.jsx
$ https://github.com/Expensify/Expensify/issues/257897
N/A
N/A
=> Add mailfence.com to list of public domains

lib/API.jsx
Remove functions for API commands that are no longer used and called from anywhere.
Part of https://github.com/Expensify/Expensify/issues/260940
None - this only removes dead code.
=> Remove unused API commands

__tests__/Str-test.js, lib/str.js
@jasperhuangg  @parasharrajat 
Adding isValidEmailMarkdown function to be used on secondary action of emails in comment
$ https://github.com/Expensify/App/issues/15620
Added tests in 'Str.isValidEmailMarkdown'
Tested using UTs and verified in platforms
<details>
https://user-images.githubusercontent.com/46707890/225723677-85b8aac6-3a8a-4f71-9375-b4c6cff8229d.mp4
</details>
<details>
https://user-images.githubusercontent.com/46707890/225723721-b397aaac-5241-4aeb-935e-120d7a10d94c.mp4
</details>
<details> …
=> Adding isValidEmailMarkdown function to be used on secondary action of emails in comment

__tests__/Str-test.js, lib/str.js
$ https://github.com/Expensify/App/pull/17447#discussion_r1169406666
1. Login in with any account
2. Logout from the app
3. Verify that the URL does not contain `?openOnAdminRoom=false` param i.e. `https://new.expensify.com`
Result:
https://user-images.githubusercontent.com/113963320/231961057-3c3f9dda-10c8-4a5b-8aae-2fb5a5ac42de.webm
Same above
=> Make Str.toBool case insensitive

lib/Logger.d.ts
Add an array to the Parameters type to resolve [TS error issue](https://github.com/Expensify/App/issues/24865#issuecomment-1727343057) during the implementation of the TS migration ticket. 
$ https://github.com/Expensify/App/issues/24865
1. Check that TS error resolved
N/A
=> Update Parameters type

lib/API.jsx
Part of https://github.com/Expensify/Web-Expensify/pull/39483#issuecomment-1805728661
None. Tested in https://github.com/Expensify/Web-Expensify/pull/39626
=> Pass domain when creating admin issued virtual card

package-lock.json, package.json
$ https://github.com/Expensify/Expensify/issues/342635
Automated tests wouldn't pass if I had broken the package.
No QA.
=> Update Semver to fix vulnerabilities

__tests__/fastMergeTest.js, lib/fastMerge.d.ts, lib/fastMerge.js
Copied fastMerge to expensify common as discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1705938537328379?thread_ts=1705673712.930129&cid=C01GTK53T8Q).
$ N/A
Copied `fastMerge` tests from `react-native-onyx` repo.
N/A
=> Copy fastMerge util from react-native-onyx

lib/CONST.d.ts, lib/CONST.jsx
https://github.com/Expensify/Expensify/issues/347634
No impact on the NewDot. The changes will be tested on the Web-E PR that will upgrade the lib version.
No impact on the NewDot. The changes will be tested on the Web-E PR that will upgrade the lib version.
=> Rename FinancialForce to Certinia

lib/CONST.d.ts, lib/ExpensiMark.js
Reverts Expensify/expensify-common#645
=> Revert "Added support for phone mention without `expensify.sms` suffix "

__tests__/ExpensiMark-HTML-test.js, lib/ExpensiMark.d.ts, lib/ExpensiMark.js
Reverts Expensify/expensify-common#640
Related to:
https://github.com/Expensify/App/issues/36437
https://github.com/Expensify/App/issues/36454
=> Revert "Add emoji rule"

__tests__/ExpensiMark-Markdown-test.js, lib/ExpensiMark.js
$ https://github.com/Expensify/App/issues/35370
PROPOSAL: https://github.com/Expensify/App/issues/35370#issuecomment-1916764860
Same as QA Steps
Same as QA Steps
Web/Desktop/iOS mWeb
2. From Slack, copy a strikethrough message
3. Paste it into the composer
4. Verify the strikethrough text is wrapped with ~ markdown
Android/iOS/Android mWeb
Can't paste an HTML
<details>
</details>
<details>
</details>
<details>
</details>
<details>
https://github.com/Expensify/expensify-common/assets/50919443/c91d627d-baf8-4ca8-bb1a-f6e2fef40176
</details>
<details> …
=> Replace s tag with strikethrough markdown

lib/ExpensiMark.js
I changed the rule of a quote regarding my proposal in Expensify/App issue
$ GH_LINK https://github.com/Expensify/App/issues/38199
I checked with nom run test and manual testing in Expensify App chat
Should validate steps from https://github.com/Expensify/App/issues/38199
=> nested quote fix

__tests__/ExpensiMark-Markdown-test.js, lib/ExpensiMark.js
$ GH_LINK https://github.com/Expensify/App/issues/40969
=> Fix phone number mention not deleting sms domain, when editing comment

lib/ExpensiMark.js, lib/str.d.ts, lib/str.js, package-lock.json, package.json
$ https://github.com/Expensify/App/issues/41078
1. Go to https://staging.new.expensify.com
2. Tap on a room report
3. Enter @+91 and send the message
4. Verify that: not consider @+91 is a valid mention.
=> feat: add is valid phone number

package-lock.json, package.json
$ https://github.com/Expensify/Expensify/issues/399651
$ https://github.com/Expensify/Expensify/issues/399653
It's a dev dependency, so if something is broken, it is the linter for jest tests. However, GH actions are passing so we should be good.
No QA.
=> Update package to fix security vulnerabilities

lib/CONST.ts
Part of https://github.com/Expensify/Expensify/issues/422418
We want to use the constant here: https://github.com/Expensify/Web-Expensify/pull/43251
N/A
N/A
=> Add HELPDOT_ROOT constant

.github/workflows/cla.yml
We only need to run cla when a PR is opened and when a commit is pushed, not when a PR is closed.
$ https://github.com/Expensify/Expensify/issues/438820
Verify that after merging this PR and a PR on App, the emergency label is not applied.
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
<details>
<summary>MacOS: Desktop</summary>
</details>
=> [No QA] Only run cla on open and synchronizefix clafix cla

lib/API.jsx
This reverts commit acb68565a7ee98078742409defa9212241e82494, reversing changes made to 67c905ca763e7bc59b248f66ed668987595c2aec.
Pure revert since this code in unused.
N/A
N/A
=> Revert "Merge pull request #825 from Expensify/cm-add-sms-delivery-command

__tests__/ExpensiMark-HTMLToText-test.js, lib/ExpensiMark.ts
$ https://github.com/Expensify/App/issues/54366
Added a unit test
- Send a video and non-image attachment to a chat
- Verify the last message shows [Attachment]
<details>
https://github.com/user-attachments/assets/f3e69a42-3324-4046-abe8-7c16a9cefa3e
</details>
<details>
https://github.com/user-attachments/assets/f24e4891-f81c-49aa-b592-8f007106c932
</details>
<details>
https://github.com/user-attachments/assets/275773c9-0d49-418c-ac13-533406852bc9
</details>
<details> …
=> Convert attachment tags to [Attachment]

.github/workflows/lint.yml, .github/workflows/test.yml, .github/workflows/typecheck.yml, package.json
- Fixed npm publish provenance (repository url in package.json was wrong)
- updates common actions from v2 to v4
- use built-in npm caching w/ normalized package.json
$ https://expensify.slack.com/archives/C06BDSWLDPB/p1740659242403509
merge to test
none
=> [No QA] Fix npm publish

lib/APIDeferred.jsx, lib/PubSub.jsx, lib/ReportHistoryStore.jsx, lib/components/form/element/combobox.js, lib/jquery.expensifyIframify.js, lib/str.ts
$ https://github.com/Expensify/Expensify/issues/489667
1. Verify `npm run test` works in Web-E.
2. Verify loading various pages works fine.
N/A, will be test in Web-E.
=> Remove undefined methods and replace them with native ones

lib/Templates.jsx, package-lock.json, package.json
Reverts Expensify/expensify-common#848
=> Revert "Bring back underscore to fix broken templates from Web-E"

lib/fastMerge.ts
$ https://github.com/Expensify/App/issues/62862
=> Convert fastmerge to worklet to be able to use it in animations on NewDot

lib/CONST.ts
Added GB currency since we still use them in the code.
Part of https://github.com/Expensify/Expensify/issues/533697
Will be tested in the Web-e PR.
N/A
=> [NO QA] Add GB currency
